package com.nhsoft.poslib.entity.order;


import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Transient;

/**
 * Payment generated by hbm2java
 */
@Entity
public class Payment{

	@Id
	@Property(nameInDb = "PAYMENT_NO")
	private String paymentNo;
	@Property(nameInDb = "ORDER_NO")
	private String orderNo;
	private String clientFid;
	private String systemBookCode;//
	private int branchNum;//
	private int shiftTableNum;//
	private String shiftTableBizday;//
	private String paymentTime;
	private String paymentPayBy;//name
	private float paymentRound;
	private float paymentReceive;
	private float paymentMoney;//
	private float paymentChange;
	private float paymentPaid;
	private float paymentBalance;
	private String paymentBillNo;
	private String paymentMemo = "";
	private String paymentAcctNo;
	private String paymentAuditor;
	private String paymentMachine;
	private int paymentCustNum;
	private float paymentCardBalance;
	private int paymentConsumeCount;
	private Boolean paymentFlag = false;
	private String paymentDate;
	private String paymentLastestDate;
	private int accountBankNum;
	private float paymentPoint;
	private Boolean consumeRevokeFlag;
	private String wechatOpenId;
	private String paymentCardPrintNum;
	@Property(nameInDb = "PAYMENT_ONLINE_UNDISCOUNT")
	private float paymentOnlineUnDiscount; //不可折扣金额
	private float paymentBuyerMoney;
	private float paymentReceiptMoney;
	private int merchantNum;
	private int stallNum;
	private String vipInfoJson;

	public String getVipInfoJson() {
		return vipInfoJson;
	}
	public void setVipInfoJson(String vipInfoJson) {
		this.vipInfoJson = vipInfoJson;
	}
	@Transient
	private boolean isUploadOk;
	@Transient
	private String cardShowInfo;
	@Transient
	private boolean isIcCard;
	@Transient
	String paymentCardUserName;
	@Transient
	String paymentCardUserTypeName;
	@Transient
	float paymentCardRedius;
	@Transient
	private String paymentCardPhone;

	public String getQuitCardJson() {
		return quitCardJson;
	}

	public void setQuitCardJson(String quitCardJson) {
		this.quitCardJson = quitCardJson;
	}

	public boolean isIcCard() {
		return isIcCard;
	}

	public void setIcCard(boolean icCard) {
		isIcCard = icCard;
	}

	@Transient
	private String quitCardJson;

	@Generated(hash = 377908534)
	public Payment(String paymentNo, String orderNo, String clientFid,
			String systemBookCode, int branchNum, int shiftTableNum,
			String shiftTableBizday, String paymentTime, String paymentPayBy,
			float paymentRound, float paymentReceive, float paymentMoney,
			float paymentChange, float paymentPaid, float paymentBalance,
			String paymentBillNo, String paymentMemo, String paymentAcctNo,
			String paymentAuditor, String paymentMachine, int paymentCustNum,
			float paymentCardBalance, int paymentConsumeCount, Boolean paymentFlag,
			String paymentDate, String paymentLastestDate, int accountBankNum,
			float paymentPoint, Boolean consumeRevokeFlag, String wechatOpenId,
			String paymentCardPrintNum, float paymentOnlineUnDiscount,
			float paymentBuyerMoney, float paymentReceiptMoney, int merchantNum,
			int stallNum, String vipInfoJson) {
		this.paymentNo = paymentNo;
		this.orderNo = orderNo;
		this.clientFid = clientFid;
		this.systemBookCode = systemBookCode;
		this.branchNum = branchNum;
		this.shiftTableNum = shiftTableNum;
		this.shiftTableBizday = shiftTableBizday;
		this.paymentTime = paymentTime;
		this.paymentPayBy = paymentPayBy;
		this.paymentRound = paymentRound;
		this.paymentReceive = paymentReceive;
		this.paymentMoney = paymentMoney;
		this.paymentChange = paymentChange;
		this.paymentPaid = paymentPaid;
		this.paymentBalance = paymentBalance;
		this.paymentBillNo = paymentBillNo;
		this.paymentMemo = paymentMemo;
		this.paymentAcctNo = paymentAcctNo;
		this.paymentAuditor = paymentAuditor;
		this.paymentMachine = paymentMachine;
		this.paymentCustNum = paymentCustNum;
		this.paymentCardBalance = paymentCardBalance;
		this.paymentConsumeCount = paymentConsumeCount;
		this.paymentFlag = paymentFlag;
		this.paymentDate = paymentDate;
		this.paymentLastestDate = paymentLastestDate;
		this.accountBankNum = accountBankNum;
		this.paymentPoint = paymentPoint;
		this.consumeRevokeFlag = consumeRevokeFlag;
		this.wechatOpenId = wechatOpenId;
		this.paymentCardPrintNum = paymentCardPrintNum;
		this.paymentOnlineUnDiscount = paymentOnlineUnDiscount;
		this.paymentBuyerMoney = paymentBuyerMoney;
		this.paymentReceiptMoney = paymentReceiptMoney;
		this.merchantNum = merchantNum;
		this.stallNum = stallNum;
		this.vipInfoJson = vipInfoJson;
	}
	@Generated(hash = 1565471489)
	public Payment() {
	}




	public boolean isUploadOk() {
		return isUploadOk;
	}

	public void setUploadOk(boolean uploadOk) {
		isUploadOk = uploadOk;
	}

	public String getPaymentCardUserName() {
		return paymentCardUserName;
	}

	public void setPaymentCardUserName(String paymentCardUserName) {
		this.paymentCardUserName = paymentCardUserName;
	}

	public String getPaymentCardUserTypeName() {
		return paymentCardUserTypeName;
	}

	public void setPaymentCardUserTypeName(String paymentCardUserTypeName) {
		this.paymentCardUserTypeName = paymentCardUserTypeName;
	}

	public float getPaymentCardRedius() {
		return paymentCardRedius;
	}

	public void setPaymentCardRedius(float paymentCardRedius) {
		this.paymentCardRedius = paymentCardRedius;
	}





	public String getPaymentNo() {
		return this.paymentNo;
	}
	public void setPaymentNo(String paymentNo) {
		this.paymentNo = paymentNo;
	}
	public String getOrderNo() {
		return this.orderNo;
	}
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}
	public String getClientFid() {
		return this.clientFid;
	}
	public void setClientFid(String clientFid) {
		this.clientFid = clientFid;
	}
	public String getSystemBookCode() {
		return this.systemBookCode;
	}
	public void setSystemBookCode(String systemBookCode) {
		this.systemBookCode = systemBookCode;
	}
	public int getBranchNum() {
		return this.branchNum;
	}

	public int getShiftTableNum() {
		return this.shiftTableNum;
	}

	public String getShiftTableBizday() {
		return this.shiftTableBizday;
	}
	public void setShiftTableBizday(String shiftTableBizday) {
		this.shiftTableBizday = shiftTableBizday;
	}
	public String getPaymentTime() {
		return this.paymentTime;
	}
	public void setPaymentTime(String paymentTime) {
		this.paymentTime = paymentTime;
	}
	public String getPaymentPayBy() {
		return this.paymentPayBy;
	}
	public void setPaymentPayBy(String paymentPayBy) {
		this.paymentPayBy = paymentPayBy;
	}
	public float getPaymentRound() {
		return this.paymentRound;
	}
	public void setPaymentRound(float paymentRound) {
		this.paymentRound = paymentRound;
	}
	public float getPaymentReceive() {
		return this.paymentReceive;
	}
	public void setPaymentReceive(float paymentReceive) {
		this.paymentReceive = paymentReceive;
	}
	public float getPaymentMoney() {
		return this.paymentMoney;
	}
	public void setPaymentMoney(float paymentMoney) {
		this.paymentMoney = paymentMoney;
	}
	public float getPaymentChange() {
		return this.paymentChange;
	}
	public void setPaymentChange(float paymentChange) {
		this.paymentChange = paymentChange;
	}
	public float getPaymentPaid() {
		return this.paymentPaid;
	}
	public void setPaymentPaid(float paymentPaid) {
		this.paymentPaid = paymentPaid;
	}
	public float getPaymentBalance() {
		return this.paymentBalance;
	}
	public void setPaymentBalance(float paymentBalance) {
		this.paymentBalance = paymentBalance;
	}
	public String getPaymentBillNo() {
		return this.paymentBillNo;
	}
	public void setPaymentBillNo(String paymentBillNo) {
		this.paymentBillNo = paymentBillNo;
	}
	public String getPaymentMemo() {
		return this.paymentMemo;
	}
	public void setPaymentMemo(String paymentMemo) {
		this.paymentMemo = paymentMemo;
	}
	public String getPaymentAcctNo() {
		return this.paymentAcctNo;
	}
	public void setPaymentAcctNo(String paymentAcctNo) {
		this.paymentAcctNo = paymentAcctNo;
	}
	public String getPaymentAuditor() {
		return this.paymentAuditor;
	}
	public void setPaymentAuditor(String paymentAuditor) {
		this.paymentAuditor = paymentAuditor;
	}
	public String getPaymentMachine() {
		return this.paymentMachine;
	}
	public void setPaymentMachine(String paymentMachine) {
		this.paymentMachine = paymentMachine;
	}
	public int getPaymentCustNum() {
		return this.paymentCustNum;
	}
	public float getPaymentCardBalance() {
		return this.paymentCardBalance;
	}
	public void setPaymentCardBalance(float paymentCardBalance) {
		this.paymentCardBalance = paymentCardBalance;
	}
	public int getPaymentConsumeCount() {
		return this.paymentConsumeCount;
	}

	public Boolean getPaymentFlag() {
		return this.paymentFlag;
	}
	public void setPaymentFlag(Boolean paymentFlag) {
		this.paymentFlag = paymentFlag;
	}
	public String getPaymentDate() {
		return this.paymentDate;
	}
	public void setPaymentDate(String paymentDate) {
		this.paymentDate = paymentDate;
	}
	public String getPaymentLastestDate() {
		return this.paymentLastestDate;
	}
	public void setPaymentLastestDate(String paymentLastestDate) {
		this.paymentLastestDate = paymentLastestDate;
	}
	public int getAccountBankNum() {
		return this.accountBankNum;
	}

	public float getPaymentPoint() {
		return this.paymentPoint;
	}
	public void setPaymentPoint(float paymentPoint) {
		this.paymentPoint = paymentPoint;
	}
	public Boolean getConsumeRevokeFlag() {
		return this.consumeRevokeFlag;
	}
	public void setConsumeRevokeFlag(Boolean consumeRevokeFlag) {
		this.consumeRevokeFlag = consumeRevokeFlag;
	}
	public float getPaymentOnlineUnDiscount() {
		return this.paymentOnlineUnDiscount;
	}
	public void setPaymentOnlineUnDiscount(float paymentOnlineUnDiscount) {
		this.paymentOnlineUnDiscount = paymentOnlineUnDiscount;
	}
	public float getPaymentBuyerMoney() {
		return this.paymentBuyerMoney;
	}
	public void setPaymentBuyerMoney(float paymentBuyerMoney) {
		this.paymentBuyerMoney = paymentBuyerMoney;
	}
	public float getPaymentReceiptMoney() {
		return this.paymentReceiptMoney;
	}
	public void setPaymentReceiptMoney(float paymentReceiptMoney) {
		this.paymentReceiptMoney = paymentReceiptMoney;
	}
	public int getMerchantNum() {
		return this.merchantNum;
	}

	public int getStallNum() {
		return this.stallNum;
	}

	public void setBranchNum(int branchNum) {
		this.branchNum = branchNum;
	}

	public void setShiftTableNum(int shiftTableNum) {
		this.shiftTableNum = shiftTableNum;
	}

	public void setPaymentCustNum(int paymentCustNum) {
		this.paymentCustNum = paymentCustNum;
	}

	public void setPaymentConsumeCount(int paymentConsumeCount) {
		this.paymentConsumeCount = paymentConsumeCount;
	}

	public void setAccountBankNum(int accountBankNum) {
		this.accountBankNum = accountBankNum;
	}

	public void setMerchantNum(int merchantNum) {
		this.merchantNum = merchantNum;
	}

	public void setStallNum(int stallNum) {
		this.stallNum = stallNum;
	}


	public String getCardShowInfo() {
		return cardShowInfo;
	}

	public void setCardShowInfo(String cardShowInfo) {
		this.cardShowInfo = cardShowInfo;
	}

	public String getPaymentCardPhone() {
		return paymentCardPhone;
	}

	public void setPaymentCardPhone(String paymentCardPhone) {
		this.paymentCardPhone = paymentCardPhone;
	}

	public String getWechatOpenId() {
		return this.wechatOpenId;
	}

	public void setWechatOpenId(String wechatOpenId) {
		this.wechatOpenId = wechatOpenId;
	}

	public String getPaymentCardPrintNum() {
		return this.paymentCardPrintNum;
	}

	public void setPaymentCardPrintNum(String paymentCardPrintNum) {
		this.paymentCardPrintNum = paymentCardPrintNum;
	}
}
