package com.nhsoft.poslib.entity.shift;

import com.nhsoft.poslib.entity.AmountPay;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * ShiftTable generated by hbm2java
 */
@Entity
public class ShiftTable{


	@Id
	private Long id;
	private int merchant_num;
	private int stall_num;
	private Date shift_table_biz_date;//开班日期 yyyy-mm-dd
	private Date shift_table_start;//接班时间
	private Date shift_table_end;//交班时间
	private int shift_table_user_num;//收银员编号
	private String shift_table_user_code;//收银员代码
	private String shift_table_user_name;//班次的收银员名称
	private boolean shift_table_closed;//是否已经交班
	private boolean shift_table_synchronized;//是否已经上传
	private boolean shift_table_need_carry;//是否有流水
	private boolean shift_table_carried;//
	private String shift_table_terminal_id;//终端标识
	private Boolean shift_table_dpc_synchronized;
	private float shift_table_actual_money;
	private float shift_table_actual_bank_money;
	private int shift_table_status;//默认0
	private String shift_table_memo;//
	private Date shift_table_last_edit_time;//班次最后修改时间
	private String system_book_code;//账套号
	private int branch_num;//分店编号
	private int shift_table_num;//班次号 规则待补充
	private String shift_table_bizday;//营业日 yyyymmdd
	private int shift_table_upload_times;//该班次上传次数，每个班次最多上传三次，三次都检验失败，不管该班次 默认为0
    private Float shift_input_cash;
    @Transient
    private List<AmountPay> orderPayTypeInfo;
    @Transient
    private List<AmountPay> cardPayTypeInfo;


    public Float getShift_input_cash() {
        return shift_input_cash;
    }

    public void setShift_input_cash(Float shift_input_cash) {
        this.shift_input_cash = shift_input_cash;
    }





	@Generated(hash = 646683939)
	public ShiftTable(Long id, int merchant_num, int stall_num,
			Date shift_table_biz_date, Date shift_table_start, Date shift_table_end,
			int shift_table_user_num, String shift_table_user_code,
			String shift_table_user_name, boolean shift_table_closed,
			boolean shift_table_synchronized, boolean shift_table_need_carry,
			boolean shift_table_carried, String shift_table_terminal_id,
			Boolean shift_table_dpc_synchronized, float shift_table_actual_money,
			float shift_table_actual_bank_money, int shift_table_status,
			String shift_table_memo, Date shift_table_last_edit_time,
			String system_book_code, int branch_num, int shift_table_num,
			String shift_table_bizday, int shift_table_upload_times,
			Float shift_input_cash) {
		this.id = id;
		this.merchant_num = merchant_num;
		this.stall_num = stall_num;
		this.shift_table_biz_date = shift_table_biz_date;
		this.shift_table_start = shift_table_start;
		this.shift_table_end = shift_table_end;
		this.shift_table_user_num = shift_table_user_num;
		this.shift_table_user_code = shift_table_user_code;
		this.shift_table_user_name = shift_table_user_name;
		this.shift_table_closed = shift_table_closed;
		this.shift_table_synchronized = shift_table_synchronized;
		this.shift_table_need_carry = shift_table_need_carry;
		this.shift_table_carried = shift_table_carried;
		this.shift_table_terminal_id = shift_table_terminal_id;
		this.shift_table_dpc_synchronized = shift_table_dpc_synchronized;
		this.shift_table_actual_money = shift_table_actual_money;
		this.shift_table_actual_bank_money = shift_table_actual_bank_money;
		this.shift_table_status = shift_table_status;
		this.shift_table_memo = shift_table_memo;
		this.shift_table_last_edit_time = shift_table_last_edit_time;
		this.system_book_code = system_book_code;
		this.branch_num = branch_num;
		this.shift_table_num = shift_table_num;
		this.shift_table_bizday = shift_table_bizday;
		this.shift_table_upload_times = shift_table_upload_times;
		this.shift_input_cash = shift_input_cash;
	}

	@Generated(hash = 1825118510)
	public ShiftTable() {
	}

	


	public Long getId() {
		return this.id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public int getMerchantNum() {
		return this.merchant_num;
	}
	public void setMerchantNum(int merchantNum) {
		this.merchant_num = merchantNum;
	}
	public int getStallNum() {
		return this.stall_num;
	}
	public void setStallNum(int stallNum) {
		this.stall_num = stallNum;
	}
	public Date getShiftTableBizDate() {
		return this.shift_table_biz_date;
	}
	public void setShiftTableBizDate(Date shiftTableBizDate) {
		this.shift_table_biz_date = shiftTableBizDate;
	}
	public Date getShiftTableStart() {
		return this.shift_table_start;
	}
	public void setShiftTableStart(Date shiftTableStart) {
		this.shift_table_start = shiftTableStart;
	}
	public Date getShiftTableEnd() {
		return this.shift_table_end;
	}
	public void setShiftTableEnd(Date shiftTableEnd) {
		this.shift_table_end = shiftTableEnd;
	}
	public int getShiftTableUserNum() {
		return this.shift_table_user_num;
	}
	public void setShiftTableUserNum(int shiftTableUserNum) {
		this.shift_table_user_num = shiftTableUserNum;
	}
	public String getShiftTableUserCode() {
		return this.shift_table_user_code;
	}
	public void setShiftTableUserCode(String shiftTableUserCode) {
		this.shift_table_user_code = shiftTableUserCode;
	}
	public String getShiftTableUserName() {
		return this.shift_table_user_name;
	}
	public void setShiftTableUserName(String shiftTableUserName) {
		this.shift_table_user_name = shiftTableUserName;
	}
	public boolean getShiftTableClosed() {
		return this.shift_table_closed;
	}
	public void setShiftTableClosed(boolean shiftTableClosed) {
		this.shift_table_closed = shiftTableClosed;
	}
	public boolean getShiftTableSynchronized() {
		return this.shift_table_synchronized;
	}
	public void setShiftTableSynchronized(boolean shiftTableSynchronized) {
		this.shift_table_synchronized = shiftTableSynchronized;
	}
	public boolean getShiftTableNeedCarry() {
		return this.shift_table_need_carry;
	}
	public void setShiftTableNeedCarry(boolean shiftTableNeedCarry) {
		this.shift_table_need_carry = shiftTableNeedCarry;
	}
	public boolean getShiftTableCarried() {
		return this.shift_table_carried;
	}
	public void setShiftTableCarried(boolean shiftTableCarried) {
		this.shift_table_carried = shiftTableCarried;
	}
	public String getShiftTableTerminalId() {
		return this.shift_table_terminal_id;
	}
	public void setShiftTableTerminalId(String shiftTableTerminalId) {
		this.shift_table_terminal_id = shiftTableTerminalId;
	}
	public Boolean getShiftTableDpcSynchronized() {
		return this.shift_table_dpc_synchronized;
	}
	public void setShiftTableDpcSynchronized(Boolean shiftTableDpcSynchronized) {
		this.shift_table_dpc_synchronized = shiftTableDpcSynchronized;
	}
	public float getShiftTableActualMoney() {
		return this.shift_table_actual_money;
	}
	public void setShiftTableActualMoney(float shiftTableActualMoney) {
		this.shift_table_actual_money = shiftTableActualMoney;
	}
	public float getShiftTableActualBankMoney() {
		return this.shift_table_actual_bank_money;
	}
	public void setShiftTableActualBankMoney(float shiftTableActualBankMoney) {
		this.shift_table_actual_bank_money = shiftTableActualBankMoney;
	}
	public int getShiftTableStatus() {
		return this.shift_table_status;
	}
	public void setShiftTableStatus(int shiftTableStatus) {
		this.shift_table_status = shiftTableStatus;
	}
	public String getShiftTableMemo() {
		return this.shift_table_memo;
	}
	public void setShiftTableMemo(String shiftTableMemo) {
		this.shift_table_memo = shiftTableMemo;
	}
	public Date getShiftTableLastEditTime() {
		return this.shift_table_last_edit_time;
	}
	public void setShiftTableLastEditTime(Date shiftTableLastEditTime) {
		this.shift_table_last_edit_time = shiftTableLastEditTime;
	}
	public String getSystemBookCode() {
		return this.system_book_code;
	}
	public void setSystemBookCode(String systemBookCode) {
		this.system_book_code = systemBookCode;
	}
	public int getBranchNum() {
		return this.branch_num;
	}
	public void setBranchNum(int branchNum) {
		this.branch_num = branchNum;
	}
	public int getShiftTableNum() {
		return this.shift_table_num;
	}
	public void setShiftTableNum(int shiftTableNum) {
		this.shift_table_num = shiftTableNum;
	}
	public String getShiftTableBizday() {
		return this.shift_table_bizday;
	}
	public void setShiftTableBizday(String shiftTableBizday) {
		this.shift_table_bizday = shiftTableBizday;
	}
	public int getShiftTableUploadTimes() {
		return this.shift_table_upload_times;
	}
	public void setShiftTableUploadTimes(int shiftTableUploadTimes) {
		this.shift_table_upload_times = shiftTableUploadTimes;
	}
	public int getMerchant_num() {
		return this.merchant_num;
	}
	public void setMerchant_num(int merchant_num) {
		this.merchant_num = merchant_num;
	}
	public int getStall_num() {
		return this.stall_num;
	}
	public void setStall_num(int stall_num) {
		this.stall_num = stall_num;
	}
	public Date getShift_table_biz_date() {
		return this.shift_table_biz_date;
	}
	public void setShift_table_biz_date(Date shift_table_biz_date) {
		this.shift_table_biz_date = shift_table_biz_date;
	}
	public Date getShift_table_start() {
		return this.shift_table_start;
	}
	public void setShift_table_start(Date shift_table_start) {
		this.shift_table_start = shift_table_start;
	}
	public Date getShift_table_end() {
		return this.shift_table_end;
	}
	public void setShift_table_end(Date shift_table_end) {
		this.shift_table_end = shift_table_end;
	}
	public int getShift_table_user_num() {
		return this.shift_table_user_num;
	}
	public void setShift_table_user_num(int shift_table_user_num) {
		this.shift_table_user_num = shift_table_user_num;
	}
	public String getShift_table_user_code() {
		return this.shift_table_user_code;
	}
	public void setShift_table_user_code(String shift_table_user_code) {
		this.shift_table_user_code = shift_table_user_code;
	}
	public String getShift_table_userName() {
		return this.shift_table_user_name;
	}
	public void setShift_table_userName(String shift_table_userName) {
		this.shift_table_user_name = shift_table_userName;
	}
	public boolean getShift_table_closed() {
		return this.shift_table_closed;
	}
	public void setShift_table_closed(boolean shift_table_closed) {
		this.shift_table_closed = shift_table_closed;
	}
	public boolean getShift_table_synchronized() {
		return this.shift_table_synchronized;
	}
	public void setShift_table_synchronized(boolean shift_table_synchronized) {
		this.shift_table_synchronized = shift_table_synchronized;
	}
	public boolean getShift_table_need_carry() {
		return this.shift_table_need_carry;
	}
	public void setShift_table_need_carry(boolean shift_table_need_carry) {
		this.shift_table_need_carry = shift_table_need_carry;
	}
	public boolean getShift_table_carried() {
		return this.shift_table_carried;
	}
	public void setShift_table_carried(boolean shift_table_carried) {
		this.shift_table_carried = shift_table_carried;
	}
	public String getShift_table_terminalId() {
		return this.shift_table_terminal_id;
	}
	public void setShift_table_terminalId(String shift_table_terminalId) {
		this.shift_table_terminal_id = shift_table_terminalId;
	}
	public Boolean getShift_table_dpc_synchronized() {
		return this.shift_table_dpc_synchronized;
	}
	public void setShift_table_dpc_synchronized(
			Boolean shift_table_dpc_synchronized) {
		this.shift_table_dpc_synchronized = shift_table_dpc_synchronized;
	}
	public float getShift_table_actual_money() {
		return this.shift_table_actual_money;
	}
	public void setShift_table_actual_money(float shift_table_actual_money) {
		this.shift_table_actual_money = shift_table_actual_money;
	}
	public float getShift_table_actual_bank_money() {
		return this.shift_table_actual_bank_money;
	}
	public void setShift_table_actual_bank_money(
			float shift_table_actual_bank_money) {
		this.shift_table_actual_bank_money = shift_table_actual_bank_money;
	}
	public int getShift_table_status() {
		return this.shift_table_status;
	}
	public void setShift_table_status(int shift_table_status) {
		this.shift_table_status = shift_table_status;
	}
	public String getShift_table_memo() {
		return this.shift_table_memo;
	}
	public void setShift_table_memo(String shift_table_memo) {
		this.shift_table_memo = shift_table_memo;
	}
	public Date getShift_table_last_edit_time() {
		return this.shift_table_last_edit_time;
	}
	public void setShift_table_last_edit_time(Date shift_table_last_edit_time) {
		this.shift_table_last_edit_time = shift_table_last_edit_time;
	}
	public String getSystem_book_code() {
		return this.system_book_code;
	}
	public void setSystem_book_code(String system_book_code) {
		this.system_book_code = system_book_code;
	}
	public int getBranch_num() {
		return this.branch_num;
	}
	public void setBranch_num(int branch_num) {
		this.branch_num = branch_num;
	}
	public int getShift_table_num() {
		return this.shift_table_num;
	}
	public void setShift_table_num(int shift_table_num) {
		this.shift_table_num = shift_table_num;
	}
	public String getShift_table_bizday() {
		return this.shift_table_bizday;
	}
	public void setShift_table_bizday(String shift_table_bizday) {
		this.shift_table_bizday = shift_table_bizday;
	}
	public int getShift_table_upload_times() {
		return this.shift_table_upload_times;
	}
	public void setShift_table_upload_times(int shift_table_upload_times) {
		this.shift_table_upload_times = shift_table_upload_times;
	}
	public String getShift_table_user_name() {
		return this.shift_table_user_name;
	}
	public void setShift_table_user_name(String shift_table_user_name) {
		this.shift_table_user_name = shift_table_user_name;
	}
	public String getShift_table_terminal_id() {
		return this.shift_table_terminal_id;
	}
	public void setShift_table_terminal_id(String shift_table_terminal_id) {
		this.shift_table_terminal_id = shift_table_terminal_id;
	}

    public List<AmountPay> getOrderPayTypeInfo() {
        return orderPayTypeInfo == null ? new ArrayList<AmountPay>() : orderPayTypeInfo;
    }

    public void setOrderPayTypeInfo(List<AmountPay> orderPayTypeInfo) {
        this.orderPayTypeInfo = orderPayTypeInfo;
    }

    public List<AmountPay> getCardPayTypeInfo() {
        return cardPayTypeInfo == null ? new ArrayList<AmountPay>() : cardPayTypeInfo;
    }

    public void setCardPayTypeInfo(List<AmountPay> cardPayTypeInfo) {
        this.cardPayTypeInfo = cardPayTypeInfo;
    }
}
