package com.nhsoft.poslib.entity.order;


import com.nhsoft.poslib.entity.PolicyDiscount;
import com.nhsoft.poslib.entity.PolicyPromotionDetail;
import com.nhsoft.poslib.entity.PolicyQuantityDetail;
import com.nhsoft.poslib.entity.PosItem;
import com.nhsoft.poslib.entity.PosItemGrade;
import com.nhsoft.poslib.utils.NumberUtil;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Transient;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * PosOrderDetail generated by hbm2java
 */
@Entity
public class PosOrderDetail implements Cloneable{

    @Id
    private Long id;
    private String orderNo;//订单号
    private int    orderDetailNum;//订单中第n个商品
    private int    itemNum;
    private String orderDetailType;//订单类型
    private String orderDetailItem;//商品名称
    private String orderDetailItemDepartment;
    private float  orderDetailStdPrice;
    private float  orderDetailPrice;
    private float  orderDetailAmount;
    private float  orderDetailMoney;
    private float  orderDetailAppendMoney;
    private float  orderDetailDiscount;
    private float  orderDetailTax;
    private float  orderDetailPaymentMoney;
    private int orderDetailStateCode;
    private String orderDetailStateName;
    private String orderDetailAuditor;
    private String orderDetailMemo = "";
    private int orderDetailItemMatrixNum;
    private String orderDetailItemSerialNumber;
    private float orderDetailCommission;
    private boolean orderDetailPolicyPromotionFlag;
    private boolean orderDetailPolicyPromotionQuantityFlag;
    private boolean orderDetailPolicyPromotionMoneyFlag;
    private boolean orderDetailPolicyPresentFlag;
    private boolean orderDetailPolicyDiscountFlag;
    private String orderDetailPolicyFid;
    private int orderDetailPolicyDetailNum;
    private float orderDetailCost;
    private float orderDetailGrossProfit;
    private Date orderDetailProducingDate;
    private String orderDetailLotNumber;
    private String orderDetailTicketUuid;
    private float orderDetailAssistAmount;
    private Integer orderDetailPromotionType;
    private String orderDetailTicketActionId;


    private int itemGradeNum;
    private String orderDetailOnlineUnit;
    private float orderDetailOnlineQty;
    private float orderDetailOnlinePrice;
    private Boolean orderDetailHasKit;
    private String systemBookCode;
    private Integer branchNum;
    private float paymentBalance;
    private Float orderDetailRound;
    private Integer stall_num;
    private Float orderDetailShareDiscount ;

    private String kitAmountStr;//分级商品明细重量记录


    public String getKitAmountStr() {
        return kitAmountStr;
    }

    public void setKitAmountStr(String kitAmountStr) {
        this.kitAmountStr = kitAmountStr;
    }

    public List<PolicyDiscount> getPolicyDiscounts() {
        return policyDiscounts;
    }

    public void setPolicyDiscounts(List<PolicyDiscount> policyDiscounts) {
        this.policyDiscounts = policyDiscounts;
    }

    @Transient
    private List<PolicyDiscount> policyDiscounts;

    @Transient
    private Boolean orderDetailPolicyPromotionQuantityFlagTwo; //表示享受偶数特价 用于不能修改数量

    @Transient
    private PolicyQuantityDetail policyQuantityDetail;//记录超量特价的价格

    public PolicyQuantityDetail getPolicyQuantityDetail() {
        return policyQuantityDetail;
    }

    public void setPolicyQuantityDetail(PolicyQuantityDetail policyQuantityDetail) {
        this.policyQuantityDetail = policyQuantityDetail;
    }


    public Boolean getOrderDetailPolicyPromotionQuantityFlagTwo() {
        return orderDetailPolicyPromotionQuantityFlagTwo;
    }

    public void setOrderDetailPolicyPromotionQuantityFlagTwo(Boolean orderDetailPolicyPromotionQuantityFlagTwo) {
        this.orderDetailPolicyPromotionQuantityFlagTwo = orderDetailPolicyPromotionQuantityFlagTwo;
    }

    public Float getOrder_detail_merchat_rate() {
        return order_detail_merchat_rate;
    }

    public void setOrder_detail_merchat_rate(Float order_detail_merchat_rate) {
        this.order_detail_merchat_rate = order_detail_merchat_rate;
    }

    private Float order_detail_merchat_rate;

    public Integer getStall_num() {
        return stall_num;
    }

    public void setStall_num(Integer stall_num) {
        this.stall_num = stall_num;
    }

    public Float getOrderDetailRound() {
        return orderDetailRound;
    }

    public void setOrderDetailRound(Float orderDetailRound) {
        this.orderDetailRound = orderDetailRound;
    }

    @Transient
    private List<PosOrderKitDetail> posOrderKitDetails = new ArrayList<PosOrderKitDetail>(0);
    @Transient
    private PosItem posItem;
    @Transient
    private PosItemGrade posItemGrade;
    @Transient
    private float residueMoney; //剩余多少钱
    @Transient
    PolicyPromotionDetail policyPromotionDetail;
    @Transient
    private float orderChangeAmount;
    @Transient
    private boolean isQuitCoupons; //退货是否退优惠劵

    @Transient
    private boolean isCheckCoupon; //检查券是否能反核销

    public boolean isCheckCoupon() {
        return isCheckCoupon;
    }

    public void setCheckCoupon(boolean checkCoupon) {
        isCheckCoupon = checkCoupon;
    }





    @Generated(hash = 1226884628)
    public PosOrderDetail(Long id, String orderNo, int orderDetailNum, int itemNum, String orderDetailType,
            String orderDetailItem, String orderDetailItemDepartment, float orderDetailStdPrice,
            float orderDetailPrice, float orderDetailAmount, float orderDetailMoney, float orderDetailAppendMoney,
            float orderDetailDiscount, float orderDetailTax, float orderDetailPaymentMoney,
            int orderDetailStateCode, String orderDetailStateName, String orderDetailAuditor,
            String orderDetailMemo, int orderDetailItemMatrixNum, String orderDetailItemSerialNumber,
            float orderDetailCommission, boolean orderDetailPolicyPromotionFlag,
            boolean orderDetailPolicyPromotionQuantityFlag, boolean orderDetailPolicyPromotionMoneyFlag,
            boolean orderDetailPolicyPresentFlag, boolean orderDetailPolicyDiscountFlag,
            String orderDetailPolicyFid, int orderDetailPolicyDetailNum, float orderDetailCost,
            float orderDetailGrossProfit, Date orderDetailProducingDate, String orderDetailLotNumber,
            String orderDetailTicketUuid, float orderDetailAssistAmount, Integer orderDetailPromotionType,
            String orderDetailTicketActionId, int itemGradeNum, String orderDetailOnlineUnit,
            float orderDetailOnlineQty, float orderDetailOnlinePrice, Boolean orderDetailHasKit,
            String systemBookCode, Integer branchNum, float paymentBalance, Float orderDetailRound,
            Integer stall_num, Float orderDetailShareDiscount, String kitAmountStr,
            Float order_detail_merchat_rate) {
        this.id = id;
        this.orderNo = orderNo;
        this.orderDetailNum = orderDetailNum;
        this.itemNum = itemNum;
        this.orderDetailType = orderDetailType;
        this.orderDetailItem = orderDetailItem;
        this.orderDetailItemDepartment = orderDetailItemDepartment;
        this.orderDetailStdPrice = orderDetailStdPrice;
        this.orderDetailPrice = orderDetailPrice;
        this.orderDetailAmount = orderDetailAmount;
        this.orderDetailMoney = orderDetailMoney;
        this.orderDetailAppendMoney = orderDetailAppendMoney;
        this.orderDetailDiscount = orderDetailDiscount;
        this.orderDetailTax = orderDetailTax;
        this.orderDetailPaymentMoney = orderDetailPaymentMoney;
        this.orderDetailStateCode = orderDetailStateCode;
        this.orderDetailStateName = orderDetailStateName;
        this.orderDetailAuditor = orderDetailAuditor;
        this.orderDetailMemo = orderDetailMemo;
        this.orderDetailItemMatrixNum = orderDetailItemMatrixNum;
        this.orderDetailItemSerialNumber = orderDetailItemSerialNumber;
        this.orderDetailCommission = orderDetailCommission;
        this.orderDetailPolicyPromotionFlag = orderDetailPolicyPromotionFlag;
        this.orderDetailPolicyPromotionQuantityFlag = orderDetailPolicyPromotionQuantityFlag;
        this.orderDetailPolicyPromotionMoneyFlag = orderDetailPolicyPromotionMoneyFlag;
        this.orderDetailPolicyPresentFlag = orderDetailPolicyPresentFlag;
        this.orderDetailPolicyDiscountFlag = orderDetailPolicyDiscountFlag;
        this.orderDetailPolicyFid = orderDetailPolicyFid;
        this.orderDetailPolicyDetailNum = orderDetailPolicyDetailNum;
        this.orderDetailCost = orderDetailCost;
        this.orderDetailGrossProfit = orderDetailGrossProfit;
        this.orderDetailProducingDate = orderDetailProducingDate;
        this.orderDetailLotNumber = orderDetailLotNumber;
        this.orderDetailTicketUuid = orderDetailTicketUuid;
        this.orderDetailAssistAmount = orderDetailAssistAmount;
        this.orderDetailPromotionType = orderDetailPromotionType;
        this.orderDetailTicketActionId = orderDetailTicketActionId;
        this.itemGradeNum = itemGradeNum;
        this.orderDetailOnlineUnit = orderDetailOnlineUnit;
        this.orderDetailOnlineQty = orderDetailOnlineQty;
        this.orderDetailOnlinePrice = orderDetailOnlinePrice;
        this.orderDetailHasKit = orderDetailHasKit;
        this.systemBookCode = systemBookCode;
        this.branchNum = branchNum;
        this.paymentBalance = paymentBalance;
        this.orderDetailRound = orderDetailRound;
        this.stall_num = stall_num;
        this.orderDetailShareDiscount = orderDetailShareDiscount;
        this.kitAmountStr = kitAmountStr;
        this.order_detail_merchat_rate = order_detail_merchat_rate;
    }

    @Generated(hash = 1296539103)
    public PosOrderDetail() {
    }

    public boolean isQuitCoupons() {
        return isQuitCoupons;
    }

    public void setQuitCoupons(boolean quitCoupons) {
        isQuitCoupons = quitCoupons;
    }



    public float getOrderChangeAmount() {
        return orderChangeAmount;
    }

    public void setOrderChangeAmount(float orderChangeAmount) {
        this.orderChangeAmount = orderChangeAmount;
    }

    public void setPosOrderKitDetails(List<PosOrderKitDetail> posOrderKitDetails){
        this.posOrderKitDetails = posOrderKitDetails;
    }

    public List<PosOrderKitDetail> getPosOrderKitDetails(){
        return this.posOrderKitDetails;
    }


    public PolicyPromotionDetail getPolicyPromotionDetail() {
        return policyPromotionDetail;
    }

    public void setPolicyPromotionDetail(PolicyPromotionDetail policyPromotionDetail) {
        this.policyPromotionDetail = policyPromotionDetail;
    }


    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public float getResidueMoney() {
        return residueMoney;
    }

    public void setResidueMoney(float residueMoney) {
        this.residueMoney = residueMoney;
    }


    public PosItemGrade getPosItemGrade() {
        return posItemGrade;
    }

    public void setPosItemGrade(PosItemGrade posItemGrade) {
        this.posItemGrade = posItemGrade;
    }



    public PosItem getPosItem() {
        return posItem;
    }

    public void setPosItem(PosItem posItem) {
        this.posItem = posItem;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOrderNo() {
        return this.orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public int getItemNum() {
        return this.itemNum;
    }

    public void setItemNum(int itemNum) {
        this.itemNum = itemNum;
    }

    public String getOrderDetailType() {
        return this.orderDetailType;
    }

    public void setOrderDetailType(String orderDetailType) {
        this.orderDetailType = orderDetailType;
    }

    public String getOrderDetailItem() {
        return this.orderDetailItem;
    }

    public void setOrderDetailItem(String orderDetailItem) {
        this.orderDetailItem = orderDetailItem;
    }

    public String getOrderDetailItemDepartment() {
        return this.orderDetailItemDepartment;
    }

    public void setOrderDetailItemDepartment(String orderDetailItemDepartment) {
        this.orderDetailItemDepartment = orderDetailItemDepartment;
    }

    public float getOrderDetailStdPrice() {
        return this.orderDetailStdPrice;
    }

    public void setOrderDetailStdPrice(float orderDetailStdPrice) {
        this.orderDetailStdPrice = orderDetailStdPrice;
    }

    public float getOrderDetailPrice() {
        return this.orderDetailPrice;
    }

    public void setOrderDetailPrice(float orderDetailPrice) {
        this.orderDetailPrice = orderDetailPrice;
    }

    public float getOrderDetailAmount() {
        return this.orderDetailAmount;
    }

    public void setOrderDetailAmount(float orderDetailAmount) {
        this.orderDetailAmount = orderDetailAmount;
    }

    public float getOrderDetailMoney() {
        return this.orderDetailMoney;
    }

    public void setOrderDetailMoney(float orderDetailMoney) {
        this.orderDetailMoney = orderDetailMoney;
    }

    public float getOrderDetailAppendMoney() {
        return this.orderDetailAppendMoney;
    }

    public void setOrderDetailAppendMoney(float orderDetailAppendMoney) {
        this.orderDetailAppendMoney = orderDetailAppendMoney;
    }

    public float getOrderDetailDiscount() {
        return this.orderDetailDiscount;
    }

    public void setOrderDetailDiscount(float orderDetailDiscount) {
        this.orderDetailDiscount = orderDetailDiscount;
    }

    public float getOrderDetailTax() {
        return this.orderDetailTax;
    }

    public void setOrderDetailTax(float orderDetailTax) {
        this.orderDetailTax = orderDetailTax;
    }

    public float getOrderDetailPaymentMoney() {
        return  NumberUtil.getNewFloat(this.orderDetailPaymentMoney);
    }

    public void setOrderDetailPaymentMoney(float orderDetailPaymentMoney) {
        this.orderDetailPaymentMoney = orderDetailPaymentMoney;
    }

    public Integer getOrderDetailStateCode() {
        return this.orderDetailStateCode;
    }

    public void setOrderDetailStateCode(Integer orderDetailStateCode) {
        this.orderDetailStateCode = orderDetailStateCode;
    }

    public String getOrderDetailStateName() {
        return this.orderDetailStateName;
    }

    public void setOrderDetailStateName(String orderDetailStateName) {
        this.orderDetailStateName = orderDetailStateName;
    }

    public String getOrderDetailAuditor() {
        return this.orderDetailAuditor;
    }

    public void setOrderDetailAuditor(String orderDetailAuditor) {
        this.orderDetailAuditor = orderDetailAuditor;
    }

    public String getOrderDetailMemo() {
        return this.orderDetailMemo;
    }

    public void setOrderDetailMemo(String orderDetailMemo) {
        this.orderDetailMemo = orderDetailMemo;
    }

    public Integer getOrderDetailItemMatrixNum() {
        return this.orderDetailItemMatrixNum;
    }

    public void setOrderDetailItemMatrixNum(Integer orderDetailItemMatrixNum) {
        this.orderDetailItemMatrixNum = orderDetailItemMatrixNum;
    }

    public String getOrderDetailItemSerialNumber() {
        return this.orderDetailItemSerialNumber;
    }

    public void setOrderDetailItemSerialNumber(String orderDetailItemSerialNumber) {
        this.orderDetailItemSerialNumber = orderDetailItemSerialNumber;
    }

    public float getOrderDetailCommission() {
        return this.orderDetailCommission;
    }

    public void setOrderDetailCommission(float orderDetailCommission) {
        this.orderDetailCommission = orderDetailCommission;
    }

    public boolean getOrderDetailPolicyPromotionFlag() {
        return this.orderDetailPolicyPromotionFlag;
    }

    public Boolean getOrderDetailPolicyPromotionQuantityFlag() {
        return this.orderDetailPolicyPromotionQuantityFlag;
    }


    public Boolean getOrderDetailPolicyPromotionMoneyFlag() {
        return this.orderDetailPolicyPromotionMoneyFlag;
    }

    public Boolean getOrderDetailPolicyPresentFlag() {
        return this.orderDetailPolicyPresentFlag;
    }


    public String getOrderDetailPolicyFid() {
        return this.orderDetailPolicyFid;
    }

    public void setOrderDetailPolicyFid(String orderDetailPolicyFid) {
        this.orderDetailPolicyFid = orderDetailPolicyFid;
    }

    public Integer getOrderDetailPolicyDetailNum() {
        return this.orderDetailPolicyDetailNum;
    }

    public void setOrderDetailPolicyDetailNum(Integer orderDetailPolicyDetailNum) {
        this.orderDetailPolicyDetailNum = orderDetailPolicyDetailNum;
    }

    public float getOrderDetailCost() {
        return this.orderDetailCost;
    }

    public void setOrderDetailCost(float orderDetailCost) {
        this.orderDetailCost = orderDetailCost;
    }

    public float getOrderDetailGrossProfit() {
        return this.orderDetailGrossProfit;
    }

    public void setOrderDetailGrossProfit(float orderDetailGrossProfit) {
        this.orderDetailGrossProfit = orderDetailGrossProfit;
    }

    public Date getOrderDetailProducingDate() {
        return this.orderDetailProducingDate;
    }

    public void setOrderDetailProducingDate(Date orderDetailProducingDate) {
        this.orderDetailProducingDate = orderDetailProducingDate;
    }

    public String getOrderDetailLotNumber() {
        return this.orderDetailLotNumber;
    }

    public void setOrderDetailLotNumber(String orderDetailLotNumber) {
        this.orderDetailLotNumber = orderDetailLotNumber;
    }

    public String getOrderDetailTicketUuid() {
        return this.orderDetailTicketUuid;
    }

    public void setOrderDetailTicketUuid(String orderDetailTicketUuid) {
        this.orderDetailTicketUuid = orderDetailTicketUuid;
    }

    public float getOrderDetailAssistAmount() {
        return this.orderDetailAssistAmount;
    }

    public void setOrderDetailAssistAmount(float orderDetailAssistAmount) {
        this.orderDetailAssistAmount = orderDetailAssistAmount;
    }

    public Integer getOrderDetailPromotionType() {
        return this.orderDetailPromotionType;
    }

    public void setOrderDetailPromotionType(Integer orderDetailPromotionType) {
        this.orderDetailPromotionType = orderDetailPromotionType;
    }

    public String getOrderDetailTicketActionId() {
        return this.orderDetailTicketActionId;
    }

    public void setOrderDetailTicketActionId(String orderDetailTicketActionId) {
        this.orderDetailTicketActionId = orderDetailTicketActionId;
    }

    public Boolean getOrderDetailPolicyDiscountFlag() {
        return this.orderDetailPolicyDiscountFlag;
    }


    public int getItemGradeNum() {
        return this.itemGradeNum;
    }

    public void setItemGradeNum(Integer itemGradeNum) {
        this.itemGradeNum = itemGradeNum;
    }

    public String getOrderDetailOnlineUnit() {
        return this.orderDetailOnlineUnit;
    }

    public void setOrderDetailOnlineUnit(String orderDetailOnlineUnit) {
        this.orderDetailOnlineUnit = orderDetailOnlineUnit;
    }

    public float getOrderDetailOnlineQty() {
        return this.orderDetailOnlineQty;
    }

    public void setOrderDetailOnlineQty(float orderDetailOnlineQty) {
        this.orderDetailOnlineQty = orderDetailOnlineQty;
    }

    public float getOrderDetailOnlinePrice() {
        return this.orderDetailOnlinePrice;
    }

    public void setOrderDetailOnlinePrice(float orderDetailOnlinePrice) {
        this.orderDetailOnlinePrice = orderDetailOnlinePrice;
    }

    public Boolean getOrderDetailHasKit() {
        return this.orderDetailHasKit;
    }

    public void setOrderDetailHasKit(Boolean orderDetailHasKit) {
        this.orderDetailHasKit = orderDetailHasKit;
    }

    public String getSystemBookCode() {
        return this.systemBookCode;
    }

    public void setSystemBookCode(String systemBookCode) {
        this.systemBookCode = systemBookCode;
    }

    public Integer getBranchNum() {
        return this.branchNum;
    }

    public void setBranchNum(Integer branchNum) {
        this.branchNum = branchNum;
    }

    public void setOrderDetailPolicyPromotionFlag(boolean orderDetailPolicyPromotionFlag) {
        this.orderDetailPolicyPromotionFlag = orderDetailPolicyPromotionFlag;
    }

    public void setOrderDetailPolicyPromotionQuantityFlag(
            boolean orderDetailPolicyPromotionQuantityFlag) {
        this.orderDetailPolicyPromotionQuantityFlag = orderDetailPolicyPromotionQuantityFlag;
    }

    public void setOrderDetailPolicyPromotionMoneyFlag(
            boolean orderDetailPolicyPromotionMoneyFlag) {
        this.orderDetailPolicyPromotionMoneyFlag = orderDetailPolicyPromotionMoneyFlag;
    }

    public void setOrderDetailPolicyPresentFlag(boolean orderDetailPolicyPresentFlag) {
        this.orderDetailPolicyPresentFlag = orderDetailPolicyPresentFlag;
    }

    public void setOrderDetailPolicyDiscountFlag(boolean orderDetailPolicyDiscountFlag) {
        this.orderDetailPolicyDiscountFlag = orderDetailPolicyDiscountFlag;
    }

    public void setOrderDetailNum(int orderDetailNum) {
        this.orderDetailNum = orderDetailNum;
    }

    public int getOrderDetailNum() {
        return orderDetailNum;
    }


    public void setOrderDetailStateCode(int orderDetailStateCode) {
        this.orderDetailStateCode = orderDetailStateCode;
    }

    public void setOrderDetailItemMatrixNum(int orderDetailItemMatrixNum) {
        this.orderDetailItemMatrixNum = orderDetailItemMatrixNum;
    }

    public void setOrderDetailPolicyDetailNum(int orderDetailPolicyDetailNum) {
        this.orderDetailPolicyDetailNum = orderDetailPolicyDetailNum;
    }

    public void setItemGradeNum(int itemGradeNum) {
        this.itemGradeNum = itemGradeNum;
    }

    public float getPaymentBalance() {
        return this.paymentBalance;
    }

    public void setPaymentBalance(float paymentBalance) {
        this.paymentBalance = paymentBalance;
    }
    /**
     * To-many relationship, resolved on first access (and after reset).
     * Changes to to-many relations are not persisted, make changes to the target entity.
     */

    public Float getOrderDetailShareDiscount() {
        return this.orderDetailShareDiscount == null ? 0 : orderDetailShareDiscount;
    }

    public void setOrderDetailShareDiscount(Float orderDetailShareDiscount) {
        this.orderDetailShareDiscount = orderDetailShareDiscount;
    }

}
