package com.nhsoft.poslib.service.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.Employee;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMPLOYEE".
*/
public class EmployeeDao extends AbstractDao<Employee, Long> {

    public static final String TABLENAME = "EMPLOYEE";

    /**
     * Properties of entity Employee.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property System_book_code = new Property(1, String.class, "system_book_code", false, "SYSTEM_BOOK_CODE");
        public final static Property Branch_num = new Property(2, int.class, "branch_num", false, "BRANCH_NUM");
        public final static Property Employee_num = new Property(3, int.class, "employee_num", false, "EMPLOYEE_NUM");
        public final static Property Employee_code = new Property(4, String.class, "employee_code", false, "EMPLOYEE_CODE");
        public final static Property Employee_name = new Property(5, String.class, "employee_name", false, "EMPLOYEE_NAME");
        public final static Property Employee_kind = new Property(6, String.class, "employee_kind", false, "EMPLOYEE_KIND");
        public final static Property Employee_linktel = new Property(7, String.class, "employee_linktel", false, "EMPLOYEE_LINKTEL");
        public final static Property Employee_actived = new Property(8, boolean.class, "employee_actived", false, "EMPLOYEE_ACTIVED");
    }


    public EmployeeDao(DaoConfig config) {
        super(config);
    }
    
    public EmployeeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EMPLOYEE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SYSTEM_BOOK_CODE\" TEXT," + // 1: system_book_code
                "\"BRANCH_NUM\" INTEGER NOT NULL ," + // 2: branch_num
                "\"EMPLOYEE_NUM\" INTEGER NOT NULL ," + // 3: employee_num
                "\"EMPLOYEE_CODE\" TEXT," + // 4: employee_code
                "\"EMPLOYEE_NAME\" TEXT," + // 5: employee_name
                "\"EMPLOYEE_KIND\" TEXT," + // 6: employee_kind
                "\"EMPLOYEE_LINKTEL\" TEXT," + // 7: employee_linktel
                "\"EMPLOYEE_ACTIVED\" INTEGER NOT NULL );"); // 8: employee_actived
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EMPLOYEE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Employee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(2, system_book_code);
        }
        stmt.bindLong(3, entity.getBranch_num());
        stmt.bindLong(4, entity.getEmployee_num());
 
        String employee_code = entity.getEmployee_code();
        if (employee_code != null) {
            stmt.bindString(5, employee_code);
        }
 
        String employee_name = entity.getEmployee_name();
        if (employee_name != null) {
            stmt.bindString(6, employee_name);
        }
 
        String employee_kind = entity.getEmployee_kind();
        if (employee_kind != null) {
            stmt.bindString(7, employee_kind);
        }
 
        String employee_linktel = entity.getEmployee_linktel();
        if (employee_linktel != null) {
            stmt.bindString(8, employee_linktel);
        }
        stmt.bindLong(9, entity.getEmployee_actived() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Employee entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(2, system_book_code);
        }
        stmt.bindLong(3, entity.getBranch_num());
        stmt.bindLong(4, entity.getEmployee_num());
 
        String employee_code = entity.getEmployee_code();
        if (employee_code != null) {
            stmt.bindString(5, employee_code);
        }
 
        String employee_name = entity.getEmployee_name();
        if (employee_name != null) {
            stmt.bindString(6, employee_name);
        }
 
        String employee_kind = entity.getEmployee_kind();
        if (employee_kind != null) {
            stmt.bindString(7, employee_kind);
        }
 
        String employee_linktel = entity.getEmployee_linktel();
        if (employee_linktel != null) {
            stmt.bindString(8, employee_linktel);
        }
        stmt.bindLong(9, entity.getEmployee_actived() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Employee readEntity(Cursor cursor, int offset) {
        Employee entity = new Employee( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // system_book_code
            cursor.getInt(offset + 2), // branch_num
            cursor.getInt(offset + 3), // employee_num
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // employee_code
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // employee_name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // employee_kind
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // employee_linktel
            cursor.getShort(offset + 8) != 0 // employee_actived
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Employee entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSystem_book_code(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBranch_num(cursor.getInt(offset + 2));
        entity.setEmployee_num(cursor.getInt(offset + 3));
        entity.setEmployee_code(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEmployee_name(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEmployee_kind(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setEmployee_linktel(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEmployee_actived(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Employee entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Employee entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Employee entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
