package com.nhsoft.poslib.service.greendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.PosItemGrade;

import com.nhsoft.poslib.entity.PosItemGradeTerminal;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POS_ITEM_GRADE_TERMINAL".
*/
public class PosItemGradeTerminalDao extends AbstractDao<PosItemGradeTerminal, Long> {

    public static final String TABLENAME = "POS_ITEM_GRADE_TERMINAL";

    /**
     * Properties of entity PosItemGradeTerminal.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Item_num = new Property(1, Long.class, "item_num", false, "ITEM_NUM");
        public final static Property Item_grade_num = new Property(2, int.class, "item_grade_num", false, "ITEM_GRADE_NUM");
        public final static Property PosItemGradeId = new Property(3, Long.class, "posItemGradeId", false, "POS_ITEM_GRADE_ID");
    }

    private DaoSession daoSession;


    public PosItemGradeTerminalDao(DaoConfig config) {
        super(config);
    }
    
    public PosItemGradeTerminalDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POS_ITEM_GRADE_TERMINAL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ITEM_NUM\" INTEGER," + // 1: item_num
                "\"ITEM_GRADE_NUM\" INTEGER NOT NULL ," + // 2: item_grade_num
                "\"POS_ITEM_GRADE_ID\" INTEGER);"); // 3: posItemGradeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POS_ITEM_GRADE_TERMINAL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PosItemGradeTerminal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long item_num = entity.getItem_num();
        if (item_num != null) {
            stmt.bindLong(2, item_num);
        }
        stmt.bindLong(3, entity.getItem_grade_num());
 
        Long posItemGradeId = entity.getPosItemGradeId();
        if (posItemGradeId != null) {
            stmt.bindLong(4, posItemGradeId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PosItemGradeTerminal entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long item_num = entity.getItem_num();
        if (item_num != null) {
            stmt.bindLong(2, item_num);
        }
        stmt.bindLong(3, entity.getItem_grade_num());
 
        Long posItemGradeId = entity.getPosItemGradeId();
        if (posItemGradeId != null) {
            stmt.bindLong(4, posItemGradeId);
        }
    }

    @Override
    protected final void attachEntity(PosItemGradeTerminal entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PosItemGradeTerminal readEntity(Cursor cursor, int offset) {
        PosItemGradeTerminal entity = new PosItemGradeTerminal( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // item_num
            cursor.getInt(offset + 2), // item_grade_num
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // posItemGradeId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PosItemGradeTerminal entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setItem_num(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setItem_grade_num(cursor.getInt(offset + 2));
        entity.setPosItemGradeId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PosItemGradeTerminal entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PosItemGradeTerminal entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PosItemGradeTerminal entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getPosItemGradeDao().getAllColumns());
            builder.append(" FROM POS_ITEM_GRADE_TERMINAL T");
            builder.append(" LEFT JOIN POS_ITEM_GRADE T0 ON T.\"POS_ITEM_GRADE_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected PosItemGradeTerminal loadCurrentDeep(Cursor cursor, boolean lock) {
        PosItemGradeTerminal entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        PosItemGrade posItemGrade = loadCurrentOther(daoSession.getPosItemGradeDao(), cursor, offset);
        entity.setPosItemGrade(posItemGrade);

        return entity;    
    }

    public PosItemGradeTerminal loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<PosItemGradeTerminal> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<PosItemGradeTerminal> list = new ArrayList<PosItemGradeTerminal>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<PosItemGradeTerminal> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<PosItemGradeTerminal> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
