package com.nhsoft.poslib.service.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.ReplaceCard;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REPLACE_CARD".
*/
public class ReplaceCardDao extends AbstractDao<ReplaceCard, Long> {

    public static final String TABLENAME = "REPLACE_CARD";

    /**
     * Properties of entity ReplaceCard.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Replace_card_fid = new Property(1, String.class, "replace_card_fid", false, "REPLACE_CARD_FID");
        public final static Property System_book_code = new Property(2, String.class, "system_book_code", false, "SYSTEM_BOOK_CODE");
        public final static Property Branch_num = new Property(3, Integer.class, "branch_num", false, "BRANCH_NUM");
        public final static Property Replace_card_cust_num = new Property(4, Integer.class, "replace_card_cust_num", false, "REPLACE_CARD_CUST_NUM");
        public final static Property Replace_card_old_printed_num = new Property(5, String.class, "replace_card_old_printed_num", false, "REPLACE_CARD_OLD_PRINTED_NUM");
        public final static Property Replace_card_old_physical_num = new Property(6, String.class, "replace_card_old_physical_num", false, "REPLACE_CARD_OLD_PHYSICAL_NUM");
        public final static Property Replace_card_old_deadline = new Property(7, String.class, "replace_card_old_deadline", false, "REPLACE_CARD_OLD_DEADLINE");
        public final static Property Replace_card_new_printed_num = new Property(8, String.class, "replace_card_new_printed_num", false, "REPLACE_CARD_NEW_PRINTED_NUM");
        public final static Property Replace_card_new_physical_num = new Property(9, String.class, "replace_card_new_physical_num", false, "REPLACE_CARD_NEW_PHYSICAL_NUM");
        public final static Property Replace_card_new_deadline = new Property(10, String.class, "replace_card_new_deadline", false, "REPLACE_CARD_NEW_DEADLINE");
        public final static Property Replace_card_operator = new Property(11, String.class, "replace_card_operator", false, "REPLACE_CARD_OPERATOR");
        public final static Property Replace_card_payment_type = new Property(12, Integer.class, "replace_card_payment_type", false, "REPLACE_CARD_PAYMENT_TYPE");
        public final static Property Replace_card_payment_type_name = new Property(13, String.class, "replace_card_payment_type_name", false, "REPLACE_CARD_PAYMENT_TYPE_NAME");
        public final static Property Replace_card_billref = new Property(14, String.class, "replace_card_billref", false, "REPLACE_CARD_BILLREF");
        public final static Property Repalce_card_bank_name = new Property(15, String.class, "repalce_card_bank_name", false, "REPALCE_CARD_BANK_NAME");
        public final static Property Replace_card_money = new Property(16, double.class, "replace_card_money", false, "REPLACE_CARD_MONEY");
        public final static Property Replace_card_memo = new Property(17, String.class, "replace_card_memo", false, "REPLACE_CARD_MEMO");
        public final static Property Replace_card_operate_time = new Property(18, String.class, "replace_card_operate_time", false, "REPLACE_CARD_OPERATE_TIME");
        public final static Property Replace_card_card_type = new Property(19, Integer.class, "replace_card_card_type", false, "REPLACE_CARD_CARD_TYPE");
        public final static Property Replace_card_branch_name = new Property(20, String.class, "replace_card_branch_name", false, "REPLACE_CARD_BRANCH_NAME");
        public final static Property Repalce_card_cust_name = new Property(21, String.class, "repalce_card_cust_name", false, "REPALCE_CARD_CUST_NAME");
        public final static Property Account_bank_num = new Property(22, Integer.class, "account_bank_num", false, "ACCOUNT_BANK_NUM");
        public final static Property Shift_table_bizday = new Property(23, String.class, "shift_table_bizday", false, "SHIFT_TABLE_BIZDAY");
        public final static Property Shift_table_num = new Property(24, Integer.class, "shift_table_num", false, "SHIFT_TABLE_NUM");
        public final static Property Replace_card_machine = new Property(25, String.class, "replace_card_machine", false, "REPLACE_CARD_MACHINE");
    }


    public ReplaceCardDao(DaoConfig config) {
        super(config);
    }
    
    public ReplaceCardDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REPLACE_CARD\" (" + //
                "\"ID\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"REPLACE_CARD_FID\" TEXT," + // 1: replace_card_fid
                "\"SYSTEM_BOOK_CODE\" TEXT," + // 2: system_book_code
                "\"BRANCH_NUM\" INTEGER," + // 3: branch_num
                "\"REPLACE_CARD_CUST_NUM\" INTEGER," + // 4: replace_card_cust_num
                "\"REPLACE_CARD_OLD_PRINTED_NUM\" TEXT," + // 5: replace_card_old_printed_num
                "\"REPLACE_CARD_OLD_PHYSICAL_NUM\" TEXT," + // 6: replace_card_old_physical_num
                "\"REPLACE_CARD_OLD_DEADLINE\" TEXT," + // 7: replace_card_old_deadline
                "\"REPLACE_CARD_NEW_PRINTED_NUM\" TEXT," + // 8: replace_card_new_printed_num
                "\"REPLACE_CARD_NEW_PHYSICAL_NUM\" TEXT," + // 9: replace_card_new_physical_num
                "\"REPLACE_CARD_NEW_DEADLINE\" TEXT," + // 10: replace_card_new_deadline
                "\"REPLACE_CARD_OPERATOR\" TEXT," + // 11: replace_card_operator
                "\"REPLACE_CARD_PAYMENT_TYPE\" INTEGER," + // 12: replace_card_payment_type
                "\"REPLACE_CARD_PAYMENT_TYPE_NAME\" TEXT," + // 13: replace_card_payment_type_name
                "\"REPLACE_CARD_BILLREF\" TEXT," + // 14: replace_card_billref
                "\"REPALCE_CARD_BANK_NAME\" TEXT," + // 15: repalce_card_bank_name
                "\"REPLACE_CARD_MONEY\" REAL NOT NULL ," + // 16: replace_card_money
                "\"REPLACE_CARD_MEMO\" TEXT," + // 17: replace_card_memo
                "\"REPLACE_CARD_OPERATE_TIME\" TEXT," + // 18: replace_card_operate_time
                "\"REPLACE_CARD_CARD_TYPE\" INTEGER," + // 19: replace_card_card_type
                "\"REPLACE_CARD_BRANCH_NAME\" TEXT," + // 20: replace_card_branch_name
                "\"REPALCE_CARD_CUST_NAME\" TEXT," + // 21: repalce_card_cust_name
                "\"ACCOUNT_BANK_NUM\" INTEGER," + // 22: account_bank_num
                "\"SHIFT_TABLE_BIZDAY\" TEXT," + // 23: shift_table_bizday
                "\"SHIFT_TABLE_NUM\" INTEGER," + // 24: shift_table_num
                "\"REPLACE_CARD_MACHINE\" TEXT);"); // 25: replace_card_machine
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REPLACE_CARD\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ReplaceCard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String replace_card_fid = entity.getReplace_card_fid();
        if (replace_card_fid != null) {
            stmt.bindString(2, replace_card_fid);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(3, system_book_code);
        }
 
        Integer branch_num = entity.getBranch_num();
        if (branch_num != null) {
            stmt.bindLong(4, branch_num);
        }
 
        Integer replace_card_cust_num = entity.getReplace_card_cust_num();
        if (replace_card_cust_num != null) {
            stmt.bindLong(5, replace_card_cust_num);
        }
 
        String replace_card_old_printed_num = entity.getReplace_card_old_printed_num();
        if (replace_card_old_printed_num != null) {
            stmt.bindString(6, replace_card_old_printed_num);
        }
 
        String replace_card_old_physical_num = entity.getReplace_card_old_physical_num();
        if (replace_card_old_physical_num != null) {
            stmt.bindString(7, replace_card_old_physical_num);
        }
 
        String replace_card_old_deadline = entity.getReplace_card_old_deadline();
        if (replace_card_old_deadline != null) {
            stmt.bindString(8, replace_card_old_deadline);
        }
 
        String replace_card_new_printed_num = entity.getReplace_card_new_printed_num();
        if (replace_card_new_printed_num != null) {
            stmt.bindString(9, replace_card_new_printed_num);
        }
 
        String replace_card_new_physical_num = entity.getReplace_card_new_physical_num();
        if (replace_card_new_physical_num != null) {
            stmt.bindString(10, replace_card_new_physical_num);
        }
 
        String replace_card_new_deadline = entity.getReplace_card_new_deadline();
        if (replace_card_new_deadline != null) {
            stmt.bindString(11, replace_card_new_deadline);
        }
 
        String replace_card_operator = entity.getReplace_card_operator();
        if (replace_card_operator != null) {
            stmt.bindString(12, replace_card_operator);
        }
 
        Integer replace_card_payment_type = entity.getReplace_card_payment_type();
        if (replace_card_payment_type != null) {
            stmt.bindLong(13, replace_card_payment_type);
        }
 
        String replace_card_payment_type_name = entity.getReplace_card_payment_type_name();
        if (replace_card_payment_type_name != null) {
            stmt.bindString(14, replace_card_payment_type_name);
        }
 
        String replace_card_billref = entity.getReplace_card_billref();
        if (replace_card_billref != null) {
            stmt.bindString(15, replace_card_billref);
        }
 
        String repalce_card_bank_name = entity.getRepalce_card_bank_name();
        if (repalce_card_bank_name != null) {
            stmt.bindString(16, repalce_card_bank_name);
        }
        stmt.bindDouble(17, entity.getReplace_card_money());
 
        String replace_card_memo = entity.getReplace_card_memo();
        if (replace_card_memo != null) {
            stmt.bindString(18, replace_card_memo);
        }
 
        String replace_card_operate_time = entity.getReplace_card_operate_time();
        if (replace_card_operate_time != null) {
            stmt.bindString(19, replace_card_operate_time);
        }
 
        Integer replace_card_card_type = entity.getReplace_card_card_type();
        if (replace_card_card_type != null) {
            stmt.bindLong(20, replace_card_card_type);
        }
 
        String replace_card_branch_name = entity.getReplace_card_branch_name();
        if (replace_card_branch_name != null) {
            stmt.bindString(21, replace_card_branch_name);
        }
 
        String repalce_card_cust_name = entity.getRepalce_card_cust_name();
        if (repalce_card_cust_name != null) {
            stmt.bindString(22, repalce_card_cust_name);
        }
 
        Integer account_bank_num = entity.getAccount_bank_num();
        if (account_bank_num != null) {
            stmt.bindLong(23, account_bank_num);
        }
 
        String shift_table_bizday = entity.getShift_table_bizday();
        if (shift_table_bizday != null) {
            stmt.bindString(24, shift_table_bizday);
        }
 
        Integer shift_table_num = entity.getShift_table_num();
        if (shift_table_num != null) {
            stmt.bindLong(25, shift_table_num);
        }
 
        String replace_card_machine = entity.getReplace_card_machine();
        if (replace_card_machine != null) {
            stmt.bindString(26, replace_card_machine);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ReplaceCard entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String replace_card_fid = entity.getReplace_card_fid();
        if (replace_card_fid != null) {
            stmt.bindString(2, replace_card_fid);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(3, system_book_code);
        }
 
        Integer branch_num = entity.getBranch_num();
        if (branch_num != null) {
            stmt.bindLong(4, branch_num);
        }
 
        Integer replace_card_cust_num = entity.getReplace_card_cust_num();
        if (replace_card_cust_num != null) {
            stmt.bindLong(5, replace_card_cust_num);
        }
 
        String replace_card_old_printed_num = entity.getReplace_card_old_printed_num();
        if (replace_card_old_printed_num != null) {
            stmt.bindString(6, replace_card_old_printed_num);
        }
 
        String replace_card_old_physical_num = entity.getReplace_card_old_physical_num();
        if (replace_card_old_physical_num != null) {
            stmt.bindString(7, replace_card_old_physical_num);
        }
 
        String replace_card_old_deadline = entity.getReplace_card_old_deadline();
        if (replace_card_old_deadline != null) {
            stmt.bindString(8, replace_card_old_deadline);
        }
 
        String replace_card_new_printed_num = entity.getReplace_card_new_printed_num();
        if (replace_card_new_printed_num != null) {
            stmt.bindString(9, replace_card_new_printed_num);
        }
 
        String replace_card_new_physical_num = entity.getReplace_card_new_physical_num();
        if (replace_card_new_physical_num != null) {
            stmt.bindString(10, replace_card_new_physical_num);
        }
 
        String replace_card_new_deadline = entity.getReplace_card_new_deadline();
        if (replace_card_new_deadline != null) {
            stmt.bindString(11, replace_card_new_deadline);
        }
 
        String replace_card_operator = entity.getReplace_card_operator();
        if (replace_card_operator != null) {
            stmt.bindString(12, replace_card_operator);
        }
 
        Integer replace_card_payment_type = entity.getReplace_card_payment_type();
        if (replace_card_payment_type != null) {
            stmt.bindLong(13, replace_card_payment_type);
        }
 
        String replace_card_payment_type_name = entity.getReplace_card_payment_type_name();
        if (replace_card_payment_type_name != null) {
            stmt.bindString(14, replace_card_payment_type_name);
        }
 
        String replace_card_billref = entity.getReplace_card_billref();
        if (replace_card_billref != null) {
            stmt.bindString(15, replace_card_billref);
        }
 
        String repalce_card_bank_name = entity.getRepalce_card_bank_name();
        if (repalce_card_bank_name != null) {
            stmt.bindString(16, repalce_card_bank_name);
        }
        stmt.bindDouble(17, entity.getReplace_card_money());
 
        String replace_card_memo = entity.getReplace_card_memo();
        if (replace_card_memo != null) {
            stmt.bindString(18, replace_card_memo);
        }
 
        String replace_card_operate_time = entity.getReplace_card_operate_time();
        if (replace_card_operate_time != null) {
            stmt.bindString(19, replace_card_operate_time);
        }
 
        Integer replace_card_card_type = entity.getReplace_card_card_type();
        if (replace_card_card_type != null) {
            stmt.bindLong(20, replace_card_card_type);
        }
 
        String replace_card_branch_name = entity.getReplace_card_branch_name();
        if (replace_card_branch_name != null) {
            stmt.bindString(21, replace_card_branch_name);
        }
 
        String repalce_card_cust_name = entity.getRepalce_card_cust_name();
        if (repalce_card_cust_name != null) {
            stmt.bindString(22, repalce_card_cust_name);
        }
 
        Integer account_bank_num = entity.getAccount_bank_num();
        if (account_bank_num != null) {
            stmt.bindLong(23, account_bank_num);
        }
 
        String shift_table_bizday = entity.getShift_table_bizday();
        if (shift_table_bizday != null) {
            stmt.bindString(24, shift_table_bizday);
        }
 
        Integer shift_table_num = entity.getShift_table_num();
        if (shift_table_num != null) {
            stmt.bindLong(25, shift_table_num);
        }
 
        String replace_card_machine = entity.getReplace_card_machine();
        if (replace_card_machine != null) {
            stmt.bindString(26, replace_card_machine);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ReplaceCard readEntity(Cursor cursor, int offset) {
        ReplaceCard entity = new ReplaceCard( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // replace_card_fid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // system_book_code
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // branch_num
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // replace_card_cust_num
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // replace_card_old_printed_num
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // replace_card_old_physical_num
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // replace_card_old_deadline
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // replace_card_new_printed_num
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // replace_card_new_physical_num
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // replace_card_new_deadline
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // replace_card_operator
            cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12), // replace_card_payment_type
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // replace_card_payment_type_name
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // replace_card_billref
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // repalce_card_bank_name
            cursor.getDouble(offset + 16), // replace_card_money
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // replace_card_memo
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // replace_card_operate_time
            cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19), // replace_card_card_type
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // replace_card_branch_name
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // repalce_card_cust_name
            cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22), // account_bank_num
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // shift_table_bizday
            cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24), // shift_table_num
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25) // replace_card_machine
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ReplaceCard entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setReplace_card_fid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSystem_book_code(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBranch_num(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setReplace_card_cust_num(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setReplace_card_old_printed_num(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setReplace_card_old_physical_num(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setReplace_card_old_deadline(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setReplace_card_new_printed_num(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setReplace_card_new_physical_num(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setReplace_card_new_deadline(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setReplace_card_operator(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setReplace_card_payment_type(cursor.isNull(offset + 12) ? null : cursor.getInt(offset + 12));
        entity.setReplace_card_payment_type_name(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setReplace_card_billref(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setRepalce_card_bank_name(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setReplace_card_money(cursor.getDouble(offset + 16));
        entity.setReplace_card_memo(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setReplace_card_operate_time(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setReplace_card_card_type(cursor.isNull(offset + 19) ? null : cursor.getInt(offset + 19));
        entity.setReplace_card_branch_name(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setRepalce_card_cust_name(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setAccount_bank_num(cursor.isNull(offset + 22) ? null : cursor.getInt(offset + 22));
        entity.setShift_table_bizday(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setShift_table_num(cursor.isNull(offset + 24) ? null : cursor.getInt(offset + 24));
        entity.setReplace_card_machine(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ReplaceCard entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ReplaceCard entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ReplaceCard entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
