package com.nhsoft.poslib.service.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.TableMd5;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TABLE_MD5".
*/
public class TableMd5Dao extends AbstractDao<TableMd5, Long> {

    public static final String TABLENAME = "TABLE_MD5";

    /**
     * Properties of entity TableMd5.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property StrKey = new Property(0, Long.class, "strKey", true, "_id");
        public final static Property StrValue = new Property(1, String.class, "strValue", false, "STR_VALUE");
    }


    public TableMd5Dao(DaoConfig config) {
        super(config);
    }
    
    public TableMd5Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TABLE_MD5\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: strKey
                "\"STR_VALUE\" TEXT);"); // 1: strValue
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TABLE_MD5\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TableMd5 entity) {
        stmt.clearBindings();
 
        Long strKey = entity.getStrKey();
        if (strKey != null) {
            stmt.bindLong(1, strKey);
        }
 
        String strValue = entity.getStrValue();
        if (strValue != null) {
            stmt.bindString(2, strValue);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TableMd5 entity) {
        stmt.clearBindings();
 
        Long strKey = entity.getStrKey();
        if (strKey != null) {
            stmt.bindLong(1, strKey);
        }
 
        String strValue = entity.getStrValue();
        if (strValue != null) {
            stmt.bindString(2, strValue);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TableMd5 readEntity(Cursor cursor, int offset) {
        TableMd5 entity = new TableMd5( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // strKey
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // strValue
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TableMd5 entity, int offset) {
        entity.setStrKey(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TableMd5 entity, long rowId) {
        entity.setStrKey(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TableMd5 entity) {
        if(entity != null) {
            return entity.getStrKey();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TableMd5 entity) {
        return entity.getStrKey() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
