package com.nhsoft.poslib.service.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.TicketSendDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TICKET_SEND_DETAIL".
*/
public class TicketSendDetailDao extends AbstractDao<TicketSendDetail, String> {

    public static final String TABLENAME = "TICKET_SEND_DETAIL";

    /**
     * Properties of entity TicketSendDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Ticket_send_fid = new Property(0, String.class, "ticket_send_fid", true, "TICKET_SEND_FID");
        public final static Property Ticket_send_detail_num = new Property(1, int.class, "ticket_send_detail_num", false, "TICKET_SEND_DETAIL_NUM");
        public final static Property Ticket_send_detail_print_num = new Property(2, String.class, "ticket_send_detail_print_num", false, "TICKET_SEND_DETAIL_PRINT_NUM");
        public final static Property Ticket_send_detail_value = new Property(3, float.class, "ticket_send_detail_value", false, "TICKET_SEND_DETAIL_VALUE");
        public final static Property Ticket_send_detail_date = new Property(4, String.class, "ticket_send_detail_date", false, "TICKET_SEND_DETAIL_DATE");
        public final static Property Ticket_send_detail_valid_date = new Property(5, String.class, "ticket_send_detail_valid_date", false, "TICKET_SEND_DETAIL_VALID_DATE");
        public final static Property Ticket_send_detail_type = new Property(6, String.class, "ticket_send_detail_type", false, "TICKET_SEND_DETAIL_TYPE");
        public final static Property Ticket_send_detail_state_code = new Property(7, int.class, "ticket_send_detail_state_code", false, "TICKET_SEND_DETAIL_STATE_CODE");
        public final static Property Ticket_send_detail_state_name = new Property(8, String.class, "ticket_send_detail_state_name", false, "TICKET_SEND_DETAIL_STATE_NAME");
        public final static Property Ticket_send_detail_memo = new Property(9, String.class, "ticket_send_detail_memo", false, "TICKET_SEND_DETAIL_MEMO");
        public final static Property Ticket_send_detail_sync_flag = new Property(10, boolean.class, "ticket_send_detail_sync_flag", false, "TICKET_SEND_DETAIL_SYNC_FLAG");
        public final static Property Ticket_send_detail_uuid = new Property(11, String.class, "ticket_send_detail_uuid", false, "TICKET_SEND_DETAIL_UUID");
        public final static Property Ticket_send_bar_code = new Property(12, String.class, "ticket_send_bar_code", false, "TICKET_SEND_BAR_CODE");
        public final static Property Ticket_send_detail_branch = new Property(13, String.class, "ticket_send_detail_branch", false, "TICKET_SEND_DETAIL_BRANCH");
        public final static Property Ticket_send_detail_branch_num = new Property(14, int.class, "ticket_send_detail_branch_num", false, "TICKET_SEND_DETAIL_BRANCH_NUM");
        public final static Property Ticket_send_detail_time = new Property(15, String.class, "ticket_send_detail_time", false, "TICKET_SEND_DETAIL_TIME");
        public final static Property Ticket_send_detail_user = new Property(16, String.class, "ticket_send_detail_user", false, "TICKET_SEND_DETAIL_USER");
        public final static Property Action_id = new Property(17, String.class, "action_id", false, "ACTION_ID");
        public final static Property Ticket_send_detail_card_num = new Property(18, int.class, "ticket_send_detail_card_num", false, "TICKET_SEND_DETAIL_CARD_NUM");
        public final static Property Ticket_send_detail_order_no = new Property(19, String.class, "ticket_send_detail_order_no", false, "TICKET_SEND_DETAIL_ORDER_NO");
        public final static Property Ticket_send_detail_order_money = new Property(20, float.class, "ticket_send_detail_order_money", false, "TICKET_SEND_DETAIL_ORDER_MONEY");
        public final static Property Ticket_send_detail_send_time = new Property(21, String.class, "ticket_send_detail_send_time", false, "TICKET_SEND_DETAIL_SEND_TIME");
        public final static Property Ticket_send_detail_send_branch = new Property(22, int.class, "ticket_send_detail_send_branch", false, "TICKET_SEND_DETAIL_SEND_BRANCH");
        public final static Property Ticket_send_detail_valid_start = new Property(23, String.class, "ticket_send_detail_valid_start", false, "TICKET_SEND_DETAIL_VALID_START");
        public final static Property Ticket_send_detail_pre_order_no = new Property(24, String.class, "ticket_send_detail_pre_order_no", false, "TICKET_SEND_DETAIL_PRE_ORDER_NO");
        public final static Property Ticket_send_detail_source = new Property(25, String.class, "ticket_send_detail_source", false, "TICKET_SEND_DETAIL_SOURCE");
        public final static Property Ticket_send_detail_use_source = new Property(26, String.class, "ticket_send_detail_use_source", false, "TICKET_SEND_DETAIL_USE_SOURCE");
        public final static Property Ticket_send_detail_password = new Property(27, String.class, "ticket_send_detail_password", false, "TICKET_SEND_DETAIL_PASSWORD");
        public final static Property Ticket_send_detail_open_id = new Property(28, String.class, "ticket_send_detail_open_id", false, "TICKET_SEND_DETAIL_OPEN_ID");
        public final static Property Ticket_send_detail_ref_bill = new Property(29, String.class, "ticket_send_detail_ref_bill", false, "TICKET_SEND_DETAIL_REF_BILL");
        public final static Property System_book_code = new Property(30, String.class, "system_book_code", false, "SYSTEM_BOOK_CODE");
        public final static Property Ticket_send_detail_phone = new Property(31, String.class, "ticket_send_detail_phone", false, "TICKET_SEND_DETAIL_PHONE");
        public final static Property Branch_num = new Property(32, int.class, "branch_num", false, "BRANCH_NUM");
        public final static Property ShiftTableNum = new Property(33, int.class, "shiftTableNum", false, "SHIFT_TABLE_NUM");
        public final static Property Ticket_send_detail_type_code = new Property(34, String.class, "ticket_send_detail_type_code", false, "TICKET_SEND_DETAIL_TYPE_CODE");
        public final static Property Coupon_action_detail_id = new Property(35, Long.class, "coupon_action_detail_id", false, "COUPON_ACTION_DETAIL_ID");
    }


    public TicketSendDetailDao(DaoConfig config) {
        super(config);
    }
    
    public TicketSendDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TICKET_SEND_DETAIL\" (" + //
                "\"TICKET_SEND_FID\" TEXT PRIMARY KEY NOT NULL ," + // 0: ticket_send_fid
                "\"TICKET_SEND_DETAIL_NUM\" INTEGER NOT NULL ," + // 1: ticket_send_detail_num
                "\"TICKET_SEND_DETAIL_PRINT_NUM\" TEXT," + // 2: ticket_send_detail_print_num
                "\"TICKET_SEND_DETAIL_VALUE\" REAL NOT NULL ," + // 3: ticket_send_detail_value
                "\"TICKET_SEND_DETAIL_DATE\" TEXT," + // 4: ticket_send_detail_date
                "\"TICKET_SEND_DETAIL_VALID_DATE\" TEXT," + // 5: ticket_send_detail_valid_date
                "\"TICKET_SEND_DETAIL_TYPE\" TEXT," + // 6: ticket_send_detail_type
                "\"TICKET_SEND_DETAIL_STATE_CODE\" INTEGER NOT NULL ," + // 7: ticket_send_detail_state_code
                "\"TICKET_SEND_DETAIL_STATE_NAME\" TEXT," + // 8: ticket_send_detail_state_name
                "\"TICKET_SEND_DETAIL_MEMO\" TEXT," + // 9: ticket_send_detail_memo
                "\"TICKET_SEND_DETAIL_SYNC_FLAG\" INTEGER NOT NULL ," + // 10: ticket_send_detail_sync_flag
                "\"TICKET_SEND_DETAIL_UUID\" TEXT," + // 11: ticket_send_detail_uuid
                "\"TICKET_SEND_BAR_CODE\" TEXT," + // 12: ticket_send_bar_code
                "\"TICKET_SEND_DETAIL_BRANCH\" TEXT," + // 13: ticket_send_detail_branch
                "\"TICKET_SEND_DETAIL_BRANCH_NUM\" INTEGER NOT NULL ," + // 14: ticket_send_detail_branch_num
                "\"TICKET_SEND_DETAIL_TIME\" TEXT," + // 15: ticket_send_detail_time
                "\"TICKET_SEND_DETAIL_USER\" TEXT," + // 16: ticket_send_detail_user
                "\"ACTION_ID\" TEXT," + // 17: action_id
                "\"TICKET_SEND_DETAIL_CARD_NUM\" INTEGER NOT NULL ," + // 18: ticket_send_detail_card_num
                "\"TICKET_SEND_DETAIL_ORDER_NO\" TEXT," + // 19: ticket_send_detail_order_no
                "\"TICKET_SEND_DETAIL_ORDER_MONEY\" REAL NOT NULL ," + // 20: ticket_send_detail_order_money
                "\"TICKET_SEND_DETAIL_SEND_TIME\" TEXT," + // 21: ticket_send_detail_send_time
                "\"TICKET_SEND_DETAIL_SEND_BRANCH\" INTEGER NOT NULL ," + // 22: ticket_send_detail_send_branch
                "\"TICKET_SEND_DETAIL_VALID_START\" TEXT," + // 23: ticket_send_detail_valid_start
                "\"TICKET_SEND_DETAIL_PRE_ORDER_NO\" TEXT," + // 24: ticket_send_detail_pre_order_no
                "\"TICKET_SEND_DETAIL_SOURCE\" TEXT," + // 25: ticket_send_detail_source
                "\"TICKET_SEND_DETAIL_USE_SOURCE\" TEXT," + // 26: ticket_send_detail_use_source
                "\"TICKET_SEND_DETAIL_PASSWORD\" TEXT," + // 27: ticket_send_detail_password
                "\"TICKET_SEND_DETAIL_OPEN_ID\" TEXT," + // 28: ticket_send_detail_open_id
                "\"TICKET_SEND_DETAIL_REF_BILL\" TEXT," + // 29: ticket_send_detail_ref_bill
                "\"SYSTEM_BOOK_CODE\" TEXT," + // 30: system_book_code
                "\"TICKET_SEND_DETAIL_PHONE\" TEXT," + // 31: ticket_send_detail_phone
                "\"BRANCH_NUM\" INTEGER NOT NULL ," + // 32: branch_num
                "\"SHIFT_TABLE_NUM\" INTEGER NOT NULL ," + // 33: shiftTableNum
                "\"TICKET_SEND_DETAIL_TYPE_CODE\" TEXT," + // 34: ticket_send_detail_type_code
                "\"COUPON_ACTION_DETAIL_ID\" INTEGER);"); // 35: coupon_action_detail_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TICKET_SEND_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TicketSendDetail entity) {
        stmt.clearBindings();
 
        String ticket_send_fid = entity.getTicket_send_fid();
        if (ticket_send_fid != null) {
            stmt.bindString(1, ticket_send_fid);
        }
        stmt.bindLong(2, entity.getTicket_send_detail_num());
 
        String ticket_send_detail_print_num = entity.getTicket_send_detail_print_num();
        if (ticket_send_detail_print_num != null) {
            stmt.bindString(3, ticket_send_detail_print_num);
        }
        stmt.bindDouble(4, entity.getTicket_send_detail_value());
 
        String ticket_send_detail_date = entity.getTicket_send_detail_date();
        if (ticket_send_detail_date != null) {
            stmt.bindString(5, ticket_send_detail_date);
        }
 
        String ticket_send_detail_valid_date = entity.getTicket_send_detail_valid_date();
        if (ticket_send_detail_valid_date != null) {
            stmt.bindString(6, ticket_send_detail_valid_date);
        }
 
        String ticket_send_detail_type = entity.getTicket_send_detail_type();
        if (ticket_send_detail_type != null) {
            stmt.bindString(7, ticket_send_detail_type);
        }
        stmt.bindLong(8, entity.getTicket_send_detail_state_code());
 
        String ticket_send_detail_state_name = entity.getTicket_send_detail_state_name();
        if (ticket_send_detail_state_name != null) {
            stmt.bindString(9, ticket_send_detail_state_name);
        }
 
        String ticket_send_detail_memo = entity.getTicket_send_detail_memo();
        if (ticket_send_detail_memo != null) {
            stmt.bindString(10, ticket_send_detail_memo);
        }
        stmt.bindLong(11, entity.getTicket_send_detail_sync_flag() ? 1L: 0L);
 
        String ticket_send_detail_uuid = entity.getTicket_send_detail_uuid();
        if (ticket_send_detail_uuid != null) {
            stmt.bindString(12, ticket_send_detail_uuid);
        }
 
        String ticket_send_bar_code = entity.getTicket_send_bar_code();
        if (ticket_send_bar_code != null) {
            stmt.bindString(13, ticket_send_bar_code);
        }
 
        String ticket_send_detail_branch = entity.getTicket_send_detail_branch();
        if (ticket_send_detail_branch != null) {
            stmt.bindString(14, ticket_send_detail_branch);
        }
        stmt.bindLong(15, entity.getTicket_send_detail_branch_num());
 
        String ticket_send_detail_time = entity.getTicket_send_detail_time();
        if (ticket_send_detail_time != null) {
            stmt.bindString(16, ticket_send_detail_time);
        }
 
        String ticket_send_detail_user = entity.getTicket_send_detail_user();
        if (ticket_send_detail_user != null) {
            stmt.bindString(17, ticket_send_detail_user);
        }
 
        String action_id = entity.getAction_id();
        if (action_id != null) {
            stmt.bindString(18, action_id);
        }
        stmt.bindLong(19, entity.getTicket_send_detail_card_num());
 
        String ticket_send_detail_order_no = entity.getTicket_send_detail_order_no();
        if (ticket_send_detail_order_no != null) {
            stmt.bindString(20, ticket_send_detail_order_no);
        }
        stmt.bindDouble(21, entity.getTicket_send_detail_order_money());
 
        String ticket_send_detail_send_time = entity.getTicket_send_detail_send_time();
        if (ticket_send_detail_send_time != null) {
            stmt.bindString(22, ticket_send_detail_send_time);
        }
        stmt.bindLong(23, entity.getTicket_send_detail_send_branch());
 
        String ticket_send_detail_valid_start = entity.getTicket_send_detail_valid_start();
        if (ticket_send_detail_valid_start != null) {
            stmt.bindString(24, ticket_send_detail_valid_start);
        }
 
        String ticket_send_detail_pre_order_no = entity.getTicket_send_detail_pre_order_no();
        if (ticket_send_detail_pre_order_no != null) {
            stmt.bindString(25, ticket_send_detail_pre_order_no);
        }
 
        String ticket_send_detail_source = entity.getTicket_send_detail_source();
        if (ticket_send_detail_source != null) {
            stmt.bindString(26, ticket_send_detail_source);
        }
 
        String ticket_send_detail_use_source = entity.getTicket_send_detail_use_source();
        if (ticket_send_detail_use_source != null) {
            stmt.bindString(27, ticket_send_detail_use_source);
        }
 
        String ticket_send_detail_password = entity.getTicket_send_detail_password();
        if (ticket_send_detail_password != null) {
            stmt.bindString(28, ticket_send_detail_password);
        }
 
        String ticket_send_detail_open_id = entity.getTicket_send_detail_open_id();
        if (ticket_send_detail_open_id != null) {
            stmt.bindString(29, ticket_send_detail_open_id);
        }
 
        String ticket_send_detail_ref_bill = entity.getTicket_send_detail_ref_bill();
        if (ticket_send_detail_ref_bill != null) {
            stmt.bindString(30, ticket_send_detail_ref_bill);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(31, system_book_code);
        }
 
        String ticket_send_detail_phone = entity.getTicket_send_detail_phone();
        if (ticket_send_detail_phone != null) {
            stmt.bindString(32, ticket_send_detail_phone);
        }
        stmt.bindLong(33, entity.getBranch_num());
        stmt.bindLong(34, entity.getShiftTableNum());
 
        String ticket_send_detail_type_code = entity.getTicket_send_detail_type_code();
        if (ticket_send_detail_type_code != null) {
            stmt.bindString(35, ticket_send_detail_type_code);
        }
 
        Long coupon_action_detail_id = entity.getCoupon_action_detail_id();
        if (coupon_action_detail_id != null) {
            stmt.bindLong(36, coupon_action_detail_id);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TicketSendDetail entity) {
        stmt.clearBindings();
 
        String ticket_send_fid = entity.getTicket_send_fid();
        if (ticket_send_fid != null) {
            stmt.bindString(1, ticket_send_fid);
        }
        stmt.bindLong(2, entity.getTicket_send_detail_num());
 
        String ticket_send_detail_print_num = entity.getTicket_send_detail_print_num();
        if (ticket_send_detail_print_num != null) {
            stmt.bindString(3, ticket_send_detail_print_num);
        }
        stmt.bindDouble(4, entity.getTicket_send_detail_value());
 
        String ticket_send_detail_date = entity.getTicket_send_detail_date();
        if (ticket_send_detail_date != null) {
            stmt.bindString(5, ticket_send_detail_date);
        }
 
        String ticket_send_detail_valid_date = entity.getTicket_send_detail_valid_date();
        if (ticket_send_detail_valid_date != null) {
            stmt.bindString(6, ticket_send_detail_valid_date);
        }
 
        String ticket_send_detail_type = entity.getTicket_send_detail_type();
        if (ticket_send_detail_type != null) {
            stmt.bindString(7, ticket_send_detail_type);
        }
        stmt.bindLong(8, entity.getTicket_send_detail_state_code());
 
        String ticket_send_detail_state_name = entity.getTicket_send_detail_state_name();
        if (ticket_send_detail_state_name != null) {
            stmt.bindString(9, ticket_send_detail_state_name);
        }
 
        String ticket_send_detail_memo = entity.getTicket_send_detail_memo();
        if (ticket_send_detail_memo != null) {
            stmt.bindString(10, ticket_send_detail_memo);
        }
        stmt.bindLong(11, entity.getTicket_send_detail_sync_flag() ? 1L: 0L);
 
        String ticket_send_detail_uuid = entity.getTicket_send_detail_uuid();
        if (ticket_send_detail_uuid != null) {
            stmt.bindString(12, ticket_send_detail_uuid);
        }
 
        String ticket_send_bar_code = entity.getTicket_send_bar_code();
        if (ticket_send_bar_code != null) {
            stmt.bindString(13, ticket_send_bar_code);
        }
 
        String ticket_send_detail_branch = entity.getTicket_send_detail_branch();
        if (ticket_send_detail_branch != null) {
            stmt.bindString(14, ticket_send_detail_branch);
        }
        stmt.bindLong(15, entity.getTicket_send_detail_branch_num());
 
        String ticket_send_detail_time = entity.getTicket_send_detail_time();
        if (ticket_send_detail_time != null) {
            stmt.bindString(16, ticket_send_detail_time);
        }
 
        String ticket_send_detail_user = entity.getTicket_send_detail_user();
        if (ticket_send_detail_user != null) {
            stmt.bindString(17, ticket_send_detail_user);
        }
 
        String action_id = entity.getAction_id();
        if (action_id != null) {
            stmt.bindString(18, action_id);
        }
        stmt.bindLong(19, entity.getTicket_send_detail_card_num());
 
        String ticket_send_detail_order_no = entity.getTicket_send_detail_order_no();
        if (ticket_send_detail_order_no != null) {
            stmt.bindString(20, ticket_send_detail_order_no);
        }
        stmt.bindDouble(21, entity.getTicket_send_detail_order_money());
 
        String ticket_send_detail_send_time = entity.getTicket_send_detail_send_time();
        if (ticket_send_detail_send_time != null) {
            stmt.bindString(22, ticket_send_detail_send_time);
        }
        stmt.bindLong(23, entity.getTicket_send_detail_send_branch());
 
        String ticket_send_detail_valid_start = entity.getTicket_send_detail_valid_start();
        if (ticket_send_detail_valid_start != null) {
            stmt.bindString(24, ticket_send_detail_valid_start);
        }
 
        String ticket_send_detail_pre_order_no = entity.getTicket_send_detail_pre_order_no();
        if (ticket_send_detail_pre_order_no != null) {
            stmt.bindString(25, ticket_send_detail_pre_order_no);
        }
 
        String ticket_send_detail_source = entity.getTicket_send_detail_source();
        if (ticket_send_detail_source != null) {
            stmt.bindString(26, ticket_send_detail_source);
        }
 
        String ticket_send_detail_use_source = entity.getTicket_send_detail_use_source();
        if (ticket_send_detail_use_source != null) {
            stmt.bindString(27, ticket_send_detail_use_source);
        }
 
        String ticket_send_detail_password = entity.getTicket_send_detail_password();
        if (ticket_send_detail_password != null) {
            stmt.bindString(28, ticket_send_detail_password);
        }
 
        String ticket_send_detail_open_id = entity.getTicket_send_detail_open_id();
        if (ticket_send_detail_open_id != null) {
            stmt.bindString(29, ticket_send_detail_open_id);
        }
 
        String ticket_send_detail_ref_bill = entity.getTicket_send_detail_ref_bill();
        if (ticket_send_detail_ref_bill != null) {
            stmt.bindString(30, ticket_send_detail_ref_bill);
        }
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(31, system_book_code);
        }
 
        String ticket_send_detail_phone = entity.getTicket_send_detail_phone();
        if (ticket_send_detail_phone != null) {
            stmt.bindString(32, ticket_send_detail_phone);
        }
        stmt.bindLong(33, entity.getBranch_num());
        stmt.bindLong(34, entity.getShiftTableNum());
 
        String ticket_send_detail_type_code = entity.getTicket_send_detail_type_code();
        if (ticket_send_detail_type_code != null) {
            stmt.bindString(35, ticket_send_detail_type_code);
        }
 
        Long coupon_action_detail_id = entity.getCoupon_action_detail_id();
        if (coupon_action_detail_id != null) {
            stmt.bindLong(36, coupon_action_detail_id);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public TicketSendDetail readEntity(Cursor cursor, int offset) {
        TicketSendDetail entity = new TicketSendDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // ticket_send_fid
            cursor.getInt(offset + 1), // ticket_send_detail_num
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ticket_send_detail_print_num
            cursor.getFloat(offset + 3), // ticket_send_detail_value
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // ticket_send_detail_date
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ticket_send_detail_valid_date
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ticket_send_detail_type
            cursor.getInt(offset + 7), // ticket_send_detail_state_code
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // ticket_send_detail_state_name
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // ticket_send_detail_memo
            cursor.getShort(offset + 10) != 0, // ticket_send_detail_sync_flag
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // ticket_send_detail_uuid
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // ticket_send_bar_code
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // ticket_send_detail_branch
            cursor.getInt(offset + 14), // ticket_send_detail_branch_num
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // ticket_send_detail_time
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // ticket_send_detail_user
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // action_id
            cursor.getInt(offset + 18), // ticket_send_detail_card_num
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // ticket_send_detail_order_no
            cursor.getFloat(offset + 20), // ticket_send_detail_order_money
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // ticket_send_detail_send_time
            cursor.getInt(offset + 22), // ticket_send_detail_send_branch
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // ticket_send_detail_valid_start
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // ticket_send_detail_pre_order_no
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // ticket_send_detail_source
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // ticket_send_detail_use_source
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // ticket_send_detail_password
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // ticket_send_detail_open_id
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // ticket_send_detail_ref_bill
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // system_book_code
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // ticket_send_detail_phone
            cursor.getInt(offset + 32), // branch_num
            cursor.getInt(offset + 33), // shiftTableNum
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // ticket_send_detail_type_code
            cursor.isNull(offset + 35) ? null : cursor.getLong(offset + 35) // coupon_action_detail_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TicketSendDetail entity, int offset) {
        entity.setTicket_send_fid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTicket_send_detail_num(cursor.getInt(offset + 1));
        entity.setTicket_send_detail_print_num(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTicket_send_detail_value(cursor.getFloat(offset + 3));
        entity.setTicket_send_detail_date(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTicket_send_detail_valid_date(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTicket_send_detail_type(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTicket_send_detail_state_code(cursor.getInt(offset + 7));
        entity.setTicket_send_detail_state_name(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTicket_send_detail_memo(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTicket_send_detail_sync_flag(cursor.getShort(offset + 10) != 0);
        entity.setTicket_send_detail_uuid(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTicket_send_bar_code(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTicket_send_detail_branch(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTicket_send_detail_branch_num(cursor.getInt(offset + 14));
        entity.setTicket_send_detail_time(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTicket_send_detail_user(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setAction_id(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTicket_send_detail_card_num(cursor.getInt(offset + 18));
        entity.setTicket_send_detail_order_no(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTicket_send_detail_order_money(cursor.getFloat(offset + 20));
        entity.setTicket_send_detail_send_time(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTicket_send_detail_send_branch(cursor.getInt(offset + 22));
        entity.setTicket_send_detail_valid_start(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTicket_send_detail_pre_order_no(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setTicket_send_detail_source(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setTicket_send_detail_use_source(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setTicket_send_detail_password(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTicket_send_detail_open_id(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTicket_send_detail_ref_bill(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setSystem_book_code(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTicket_send_detail_phone(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setBranch_num(cursor.getInt(offset + 32));
        entity.setShiftTableNum(cursor.getInt(offset + 33));
        entity.setTicket_send_detail_type_code(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setCoupon_action_detail_id(cursor.isNull(offset + 35) ? null : cursor.getLong(offset + 35));
     }
    
    @Override
    protected final String updateKeyAfterInsert(TicketSendDetail entity, long rowId) {
        return entity.getTicket_send_fid();
    }
    
    @Override
    public String getKey(TicketSendDetail entity) {
        if(entity != null) {
            return entity.getTicket_send_fid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TicketSendDetail entity) {
        return entity.getTicket_send_fid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
