package com.nhsoft.poslib.service.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nhsoft.poslib.entity.BookResource;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BOOK_RESOURCE".
*/
public class BookResourceDao extends AbstractDao<BookResource, Long> {

    public static final String TABLENAME = "BOOK_RESOURCE";

    /**
     * Properties of entity BookResource.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SystemBookCode = new Property(1, String.class, "systemBookCode", false, "SYSTEM_BOOK_CODE");
        public final static Property BookResourceName = new Property(2, String.class, "bookResourceName", false, "BOOK_RESOURCE_NAME");
        public final static Property BookResourceParam = new Property(3, String.class, "bookResourceParam", false, "BOOK_RESOURCE_PARAM");
    }


    public BookResourceDao(DaoConfig config) {
        super(config);
    }
    
    public BookResourceDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BOOK_RESOURCE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SYSTEM_BOOK_CODE\" TEXT," + // 1: systemBookCode
                "\"BOOK_RESOURCE_NAME\" TEXT," + // 2: bookResourceName
                "\"BOOK_RESOURCE_PARAM\" TEXT);"); // 3: bookResourceParam
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BOOK_RESOURCE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BookResource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String systemBookCode = entity.getSystemBookCode();
        if (systemBookCode != null) {
            stmt.bindString(2, systemBookCode);
        }
 
        String bookResourceName = entity.getBookResourceName();
        if (bookResourceName != null) {
            stmt.bindString(3, bookResourceName);
        }
 
        String bookResourceParam = entity.getBookResourceParam();
        if (bookResourceParam != null) {
            stmt.bindString(4, bookResourceParam);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BookResource entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String systemBookCode = entity.getSystemBookCode();
        if (systemBookCode != null) {
            stmt.bindString(2, systemBookCode);
        }
 
        String bookResourceName = entity.getBookResourceName();
        if (bookResourceName != null) {
            stmt.bindString(3, bookResourceName);
        }
 
        String bookResourceParam = entity.getBookResourceParam();
        if (bookResourceParam != null) {
            stmt.bindString(4, bookResourceParam);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BookResource readEntity(Cursor cursor, int offset) {
        BookResource entity = new BookResource( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // systemBookCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bookResourceName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // bookResourceParam
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BookResource entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSystemBookCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBookResourceName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBookResourceParam(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BookResource entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BookResource entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BookResource entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
