package com.nhsoft.poslib.service.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.nhsoft.poslib.entity.PolicyDiscountDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POLICY_DISCOUNT_DETAIL".
*/
public class PolicyDiscountDetailDao extends AbstractDao<PolicyDiscountDetail, Long> {

    public static final String TABLENAME = "POLICY_DISCOUNT_DETAIL";

    /**
     * Properties of entity PolicyDiscountDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Policy_discount_no = new Property(1, String.class, "policy_discount_no", false, "POLICY_DISCOUNT_NO");
        public final static Property Policy_discount_detail_num = new Property(2, int.class, "policy_discount_detail_num", false, "POLICY_DISCOUNT_DETAIL_NUM");
        public final static Property Item_num = new Property(3, int.class, "item_num", false, "ITEM_NUM");
        public final static Property System_book_code = new Property(4, String.class, "system_book_code", false, "SYSTEM_BOOK_CODE");
        public final static Property Policy_discount_detail_memo = new Property(5, String.class, "policy_discount_detail_memo", false, "POLICY_DISCOUNT_DETAIL_MEMO");
        public final static Property Branch_num = new Property(6, int.class, "branch_num", false, "BRANCH_NUM");
    }

    private Query<PolicyDiscountDetail> policyDiscount_Policy_discount_detailsQuery;

    public PolicyDiscountDetailDao(DaoConfig config) {
        super(config);
    }
    
    public PolicyDiscountDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POLICY_DISCOUNT_DETAIL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"POLICY_DISCOUNT_NO\" TEXT," + // 1: policy_discount_no
                "\"POLICY_DISCOUNT_DETAIL_NUM\" INTEGER NOT NULL ," + // 2: policy_discount_detail_num
                "\"ITEM_NUM\" INTEGER NOT NULL ," + // 3: item_num
                "\"SYSTEM_BOOK_CODE\" TEXT," + // 4: system_book_code
                "\"POLICY_DISCOUNT_DETAIL_MEMO\" TEXT," + // 5: policy_discount_detail_memo
                "\"BRANCH_NUM\" INTEGER NOT NULL );"); // 6: branch_num
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POLICY_DISCOUNT_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PolicyDiscountDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String policy_discount_no = entity.getPolicy_discount_no();
        if (policy_discount_no != null) {
            stmt.bindString(2, policy_discount_no);
        }
        stmt.bindLong(3, entity.getPolicy_discount_detail_num());
        stmt.bindLong(4, entity.getItem_num());
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(5, system_book_code);
        }
 
        String policy_discount_detail_memo = entity.getPolicy_discount_detail_memo();
        if (policy_discount_detail_memo != null) {
            stmt.bindString(6, policy_discount_detail_memo);
        }
        stmt.bindLong(7, entity.getBranch_num());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PolicyDiscountDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String policy_discount_no = entity.getPolicy_discount_no();
        if (policy_discount_no != null) {
            stmt.bindString(2, policy_discount_no);
        }
        stmt.bindLong(3, entity.getPolicy_discount_detail_num());
        stmt.bindLong(4, entity.getItem_num());
 
        String system_book_code = entity.getSystem_book_code();
        if (system_book_code != null) {
            stmt.bindString(5, system_book_code);
        }
 
        String policy_discount_detail_memo = entity.getPolicy_discount_detail_memo();
        if (policy_discount_detail_memo != null) {
            stmt.bindString(6, policy_discount_detail_memo);
        }
        stmt.bindLong(7, entity.getBranch_num());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PolicyDiscountDetail readEntity(Cursor cursor, int offset) {
        PolicyDiscountDetail entity = new PolicyDiscountDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // policy_discount_no
            cursor.getInt(offset + 2), // policy_discount_detail_num
            cursor.getInt(offset + 3), // item_num
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // system_book_code
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // policy_discount_detail_memo
            cursor.getInt(offset + 6) // branch_num
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PolicyDiscountDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPolicy_discount_no(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPolicy_discount_detail_num(cursor.getInt(offset + 2));
        entity.setItem_num(cursor.getInt(offset + 3));
        entity.setSystem_book_code(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPolicy_discount_detail_memo(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBranch_num(cursor.getInt(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PolicyDiscountDetail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PolicyDiscountDetail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PolicyDiscountDetail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "policy_discount_details" to-many relationship of PolicyDiscount. */
    public List<PolicyDiscountDetail> _queryPolicyDiscount_Policy_discount_details(String policy_discount_no) {
        synchronized (this) {
            if (policyDiscount_Policy_discount_detailsQuery == null) {
                QueryBuilder<PolicyDiscountDetail> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Policy_discount_no.eq(null));
                policyDiscount_Policy_discount_detailsQuery = queryBuilder.build();
            }
        }
        Query<PolicyDiscountDetail> query = policyDiscount_Policy_discount_detailsQuery.forCurrentThread();
        query.setParameter(0, policy_discount_no);
        return query.list();
    }

}
